<a href="https://colab.research.google.com/github/NishmthaM/Python_pandas/blob/main/python_pandas02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Groupby in pandas**  # can do the group of data

In [1]:
import pandas as pd

In [3]:
a= pd.DataFrame({ "name": ["Bob","Steve","Will","Robin","Dustin","Mike"],
                  "Subject": [1,2,3,4,5,6],
                  "Subject_02":[10,20,30,40,50,60]})
a

     name  Subject  Subject_02
0     Bob        1          10
1   Steve        2          20
2    Will        3          30
3   Robin        4          40
4  Dustin        5          50
5    Mike        6          60

In [4]:
b=a.groupby("name")
b

In [7]:
for x,y in b:
  print(x)
  print()
  print(y)
  print()

Bob

  name  Subject  Subject_02
0  Bob        1          10

Dustin

     name  Subject  Subject_02
4  Dustin        5          50

Mike

   name  Subject  Subject_02
5  Mike        6          60

Robin

    name  Subject  Subject_02
3  Robin        4          40

Steve

    name  Subject  Subject_02
1  Steve        2          20

Will

   name  Subject  Subject_02
2  Will        3          30

In [8]:
# to get one group data

b.get_group("Bob")

  name  Subject  Subject_02
0  Bob        1          10

In [9]:
b.get_group("Mike")

   name  Subject  Subject_02
5  Mike        6          60

In [14]:
a.min()

name          Bob
Subject         1
Subject_02     10
dtype: object

In [12]:
a.max()

name          Will
Subject          6
Subject_02      60
dtype: object

In [16]:
list(b)  # to create a list

[('Bob',
    name  Subject  Subject_02
  0  Bob        1          10),
 ('Dustin',
       name  Subject  Subject_02
  4  Dustin        5          50),
 ('Mike',
     name  Subject  Subject_02
  5  Mike        6          60),
 ('Robin',
      name  Subject  Subject_02
  3  Robin        4          40),
 ('Steve',
      name  Subject  Subject_02
  1  Steve        2          20),
 ('Will',
     name  Subject  Subject_02
  2  Will        3          30)]

**Join and Append in pandas**

In [17]:
# Join funciton

import pandas as pd

a= pd.DataFrame({"A":[1,2,3,4,5],"B":[6,7,8,9,10]})
b= pd.DataFrame({"C":[10,20,30,40,55],"D":[60,70,80,90,100]})

a.join(b)

   A   B   C    D
0  1   6  10   60
1  2   7  20   70
2  3   8  30   80
3  4   9  40   90
4  5  10  55  100

In [19]:
# Can also work in the unmatched data/ values

import pandas as pd

a= pd.DataFrame({"A":[1,2,3,4,5],"B":[6,7,8,9,10]})
b= pd.DataFrame({"C":[10,20,30],"D":[60,70,80]})

a.join(b)

   A   B     C     D
0  1   6  10.0  60.0
1  2   7  20.0  70.0
2  3   8  30.0  80.0
3  4   9   NaN   NaN
4  5  10   NaN   NaN

In [22]:

# can change the index value

import pandas as pd

a= pd.DataFrame({"A":[1,2,3,4,5],"B":[6,7,8,9,10]},index=["a","b","c","d","e"])
b= pd.DataFrame({"C":[10,20,30],"D":[60,70,80]},index=["a","b","c"])

b.join(a)

    C   D  A  B
a  10  60  1  6
b  20  70  2  7
c  30  80  3  8

In [23]:
a.join(b)

   A   B     C     D
a  1   6  10.0  60.0
b  2   7  20.0  70.0
c  3   8  30.0  80.0
d  4   9   NaN   NaN
e  5  10   NaN   NaN

In [24]:
b.join(a,how="right")

      C     D  A   B
a  10.0  60.0  1   6
b  20.0  70.0  2   7
c  30.0  80.0  3   8
d   NaN   NaN  4   9
e   NaN   NaN  5  10

In [25]:
b.join(a,how="left")

    C   D  A  B
a  10  60  1  6
b  20  70  2  7
c  30  80  3  8

In [26]:
b.join(a,how="outer")  # union

      C     D  A   B
a  10.0  60.0  1   6
b  20.0  70.0  2   7
c  30.0  80.0  3   8
d   NaN   NaN  4   9
e   NaN   NaN  5  10

In [28]:
b.join(a,how="inner")  # intersecton

    C   D  A  B
a  10  60  1  6
b  20  70  2  7
c  30  80  3  8

In [38]:
# a.join(b,how="inner",lsuffix="_12",rsuffix="_10")

**Append**

In [39]:
# Even if the data is same it will add