<a href="https://colab.research.google.com/github/NishmthaM/Python_pandas/blob/main/python_pandas02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Groupby in pandas**  # can do the group of data

In [1]:
import pandas as pd

In [3]:
a= pd.DataFrame({ "name": ["Bob","Steve","Will","Robin","Dustin","Mike"],
                  "Subject": [1,2,3,4,5,6],
                  "Subject_02":[10,20,30,40,50,60]})
a

     name  Subject  Subject_02
0     Bob        1          10
1   Steve        2          20
2    Will        3          30
3   Robin        4          40
4  Dustin        5          50
5    Mike        6          60

In [4]:
b=a.groupby("name")
b

In [7]:
for x,y in b:
  print(x)
  print()
  print(y)
  print()

Bob

  name  Subject  Subject_02
0  Bob        1          10

Dustin

     name  Subject  Subject_02
4  Dustin        5          50

Mike

   name  Subject  Subject_02
5  Mike        6          60

Robin

    name  Subject  Subject_02
3  Robin        4          40

Steve

    name  Subject  Subject_02
1  Steve        2          20

Will

   name  Subject  Subject_02
2  Will        3          30

In [8]:
# to get one group data

b.get_group("Bob")

  name  Subject  Subject_02
0  Bob        1          10

In [9]:
b.get_group("Mike")

   name  Subject  Subject_02
5  Mike        6          60

In [14]:
a.min()

name          Bob
Subject         1
Subject_02     10
dtype: object

In [12]:
a.max()

name          Will
Subject          6
Subject_02      60
dtype: object

In [16]:
list(b)  # to create a list

[('Bob',
    name  Subject  Subject_02
  0  Bob        1          10),
 ('Dustin',
       name  Subject  Subject_02
  4  Dustin        5          50),
 ('Mike',
     name  Subject  Subject_02
  5  Mike        6          60),
 ('Robin',
      name  Subject  Subject_02
  3  Robin        4          40),
 ('Steve',
      name  Subject  Subject_02
  1  Steve        2          20),
 ('Will',
     name  Subject  Subject_02
  2  Will        3          30)]