<a href="https://colab.research.google.com/github/NishmthaM/Python_pandas/blob/main/python_pandas02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Groupby in pandas**  # can do the group of data

In [2]:
import pandas as pd

In [3]:
a= pd.DataFrame({ "name": ["Bob","Steve","Will","Robin","Dustin","Mike"],
                  "Subject": [1,2,3,4,5,6],
                  "Subject_02":[10,20,30,40,50,60]})
a

     name  Subject  Subject_02
0     Bob        1          10
1   Steve        2          20
2    Will        3          30
3   Robin        4          40
4  Dustin        5          50
5    Mike        6          60

In [4]:
b=a.groupby("name")
b

In [5]:
for x,y in b:
  print(x)
  print()
  print(y)
  print()

Bob

  name  Subject  Subject_02
0  Bob        1          10

Dustin

     name  Subject  Subject_02
4  Dustin        5          50

Mike

   name  Subject  Subject_02
5  Mike        6          60

Robin

    name  Subject  Subject_02
3  Robin        4          40

Steve

    name  Subject  Subject_02
1  Steve        2          20

Will

   name  Subject  Subject_02
2  Will        3          30

In [6]:
# to get one group data

b.get_group("Bob")

  name  Subject  Subject_02
0  Bob        1          10

In [7]:
b.get_group("Mike")

   name  Subject  Subject_02
5  Mike        6          60

In [8]:
a.min()

name          Bob
Subject         1
Subject_02     10
dtype: object

In [9]:
a.max()

name          Will
Subject          6
Subject_02      60
dtype: object

In [10]:
list(b)  # to create a list

[('Bob',
    name  Subject  Subject_02
  0  Bob        1          10),
 ('Dustin',
       name  Subject  Subject_02
  4  Dustin        5          50),
 ('Mike',
     name  Subject  Subject_02
  5  Mike        6          60),
 ('Robin',
      name  Subject  Subject_02
  3  Robin        4          40),
 ('Steve',
      name  Subject  Subject_02
  1  Steve        2          20),
 ('Will',
     name  Subject  Subject_02
  2  Will        3          30)]

**Join and Append in pandas**

In [11]:
# Join funciton

import pandas as pd

a= pd.DataFrame({"A":[1,2,3,4,5],"B":[6,7,8,9,10]})
b= pd.DataFrame({"C":[10,20,30,40,55],"D":[60,70,80,90,100]})

a.join(b)

   A   B   C    D
0  1   6  10   60
1  2   7  20   70
2  3   8  30   80
3  4   9  40   90
4  5  10  55  100

In [12]:
# Can also work in the unmatched data/ values

import pandas as pd

a= pd.DataFrame({"A":[1,2,3,4,5],"B":[6,7,8,9,10]})
b= pd.DataFrame({"C":[10,20,30],"D":[60,70,80]})

a.join(b)

   A   B     C     D
0  1   6  10.0  60.0
1  2   7  20.0  70.0
2  3   8  30.0  80.0
3  4   9   NaN   NaN
4  5  10   NaN   NaN

In [13]:

# can change the index value

import pandas as pd

a= pd.DataFrame({"A":[1,2,3,4,5],"B":[6,7,8,9,10]},index=["a","b","c","d","e"])
b= pd.DataFrame({"C":[10,20,30],"D":[60,70,80]},index=["a","b","c"])

b.join(a)

    C   D  A  B
a  10  60  1  6
b  20  70  2  7
c  30  80  3  8

In [14]:
a.join(b)

   A   B     C     D
a  1   6  10.0  60.0
b  2   7  20.0  70.0
c  3   8  30.0  80.0
d  4   9   NaN   NaN
e  5  10   NaN   NaN

In [15]:
b.join(a,how="right")

      C     D  A   B
a  10.0  60.0  1   6
b  20.0  70.0  2   7
c  30.0  80.0  3   8
d   NaN   NaN  4   9
e   NaN   NaN  5  10

In [16]:
b.join(a,how="left")

    C   D  A  B
a  10  60  1  6
b  20  70  2  7
c  30  80  3  8

In [17]:
b.join(a,how="outer")  # union

      C     D  A   B
a  10.0  60.0  1   6
b  20.0  70.0  2   7
c  30.0  80.0  3   8
d   NaN   NaN  4   9
e   NaN   NaN  5  10

In [18]:
b.join(a,how="inner")  # intersecton

    C   D  A  B
a  10  60  1  6
b  20  70  2  7
c  30  80  3  8

In [19]:
# a.join(b,how="inner",lsuffix="_12",rsuffix="_10")

**Append**

In [20]:
# Even if the data is same it will add

In [29]:
import pandas as pd

a= pd.DataFrame({"A":[1,2,3,4,5],"B":[6,7,8,9,10]})
b= pd.DataFrame({"C":[10,20,30],"D":[60,70,80]})

# a.append(b) old method
pd.concat([a,b], ignore_index= True )   # new method

     A     B     C     D
0  1.0   6.0   NaN   NaN
1  2.0   7.0   NaN   NaN
2  3.0   8.0   NaN   NaN
3  4.0   9.0   NaN   NaN
4  5.0  10.0   NaN   NaN
5  NaN   NaN  10.0  60.0
6  NaN   NaN  20.0  70.0
7  NaN   NaN  30.0  80.0

**Pivot Table and Melt Function in pandas**

In [30]:
# Melt function (Melt())
# file reshaping

import pandas as pd

a=pd.DataFrame({"Days":[1,2,3,4,5,6],"Eng":[12,15,13,14,10,11],"Math":[10,15,14,18,16,12]})
a

   Days  Eng  Math
0     1   12    10
1     2   15    15
2     3   13    14
3     4   14    18
4     5   10    16
5     6   11    12

In [31]:
pd.melt(a)

   variable  value
0      Days      1
1      Days      2
2      Days      3
3      Days      4
4      Days      5
5      Days      6
6       Eng     12
7       Eng     15
8       Eng     13
9       Eng     14
10      Eng     10
11      Eng     11
12     Math     10
13     Math     15
14     Math     14
15     Math     18
16     Math     16
17     Math     12

In [36]:
# creating specific id

pd.melt(a,id_vars={"Days"})

    Days variable  value
0      1      Eng     12
1      2      Eng     15
2      3      Eng     13
3      4      Eng     14
4      5      Eng     10
5      6      Eng     11
6      1     Math     10
7      2     Math     15
8      3     Math     14
9      4     Math     18
10     5     Math     16
11     6     Math     12

In [37]:
pd.melt(a,id_vars={"Days","Eng"})

   Days  Eng variable  value
0     1   12     Math     10
1     2   15     Math     15
2     3   13     Math     14
3     4   14     Math     18
4     5   10     Math     16
5     6   11     Math     12

In [39]:
# pivot() data arrangement and reframing

import pandas as pd

a=pd.DataFrame({"Days":[1,2,3,4,5,6],"Student":["Robin","Steve","Dustin","Will","Eleven","Max"],"Eng":[12,15,13,14,10,11],"Math":[10,15,14,18,16,12]})
a

   Days Student  Eng  Math
0     1   Robin   12    10
1     2   Steve   15    15
2     3  Dustin   13    14
3     4    Will   14    18
4     5  Eleven   10    16
5     6     Max   11    12

In [43]:
a.pivot(index="Days",columns="Student")

           Eng                                  Math                           \
Student Dustin Eleven   Max Robin Steve  Will Dustin Eleven   Max Robin Steve
Days
1          NaN    NaN   NaN  12.0   NaN   NaN    NaN    NaN   NaN  10.0   NaN
2          NaN    NaN   NaN   NaN  15.0   NaN    NaN    NaN   NaN   NaN  15.0
3         13.0    NaN   NaN   NaN   NaN   NaN   14.0    NaN   NaN   NaN   NaN
4          NaN    NaN   NaN   NaN   NaN  14.0    NaN    NaN   NaN   NaN   NaN
5          NaN   10.0   NaN   NaN   NaN   NaN    NaN   16.0   NaN   NaN   NaN
6          NaN    NaN  11.0   NaN   NaN   NaN    NaN    NaN  12.0   NaN   NaN


Student  Will
Days
1         NaN
2         NaN
3         NaN
4        18.0
5         NaN
6         NaN

In [44]:
a.pivot(index="Days",columns="Student",values="Eng")

Student  Dustin  Eleven   Max  Robin  Steve  Will
Days
1           NaN     NaN   NaN   12.0    NaN   NaN
2           NaN     NaN   NaN    NaN   15.0   NaN
3          13.0     NaN   NaN    NaN    NaN   NaN
4           NaN     NaN   NaN    NaN    NaN  14.0
5           NaN    10.0   NaN    NaN    NaN   NaN
6           NaN     NaN  11.0    NaN    NaN   NaN

In [46]:
# aggfunc : aggregate function

a.pivot_table(index="Days",columns="Days",aggfunc="sum")

       Eng                                Math                                \
Days     1     2     3     4     5     6     1     2     3     4     5     6
Days
1     12.0   NaN   NaN   NaN   NaN   NaN  10.0   NaN   NaN   NaN   NaN   NaN
2      NaN  15.0   NaN   NaN   NaN   NaN   NaN  15.0   NaN   NaN   NaN   NaN
3      NaN   NaN  13.0   NaN   NaN   NaN   NaN   NaN  14.0   NaN   NaN   NaN
4      NaN   NaN   NaN  14.0   NaN   NaN   NaN   NaN   NaN  18.0   NaN   NaN
5      NaN   NaN   NaN   NaN  10.0   NaN   NaN   NaN   NaN   NaN  16.0   NaN
6      NaN   NaN   NaN   NaN   NaN  11.0   NaN   NaN   NaN   NaN   NaN  12.0

     Student
Days       1      2       3     4       5    6
Days
1      Robin    NaN     NaN   NaN     NaN  NaN
2        NaN  Steve     NaN   NaN     NaN  NaN
3        NaN    NaN  Dustin   NaN     NaN  NaN
4        NaN    NaN     NaN  Will     NaN  NaN
5        NaN    NaN     NaN   NaN  Eleven  NaN
6        NaN    NaN     NaN   NaN     NaN  Max