<a href="https://colab.research.google.com/github/NishmthaM/Python_pandas/blob/main/Python_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# what is pandas?
# It has reference for both "panel data" and "python data analysis".Used to work with data set
# (fubctions) analyzing,cleaning,exploring,and manipulating data
# Read and write data structures and different formates: CSV,text.XML,JSON,ZIP etc
# For large amount of data like(lakhs of data) in excel it is not possible so we use pandas

In [4]:
# To install (pip install pandas)
# To import (import pandas as pd)

In [5]:
# data structure in pandas
# series, dataframes, panel

In [6]:
# Series: 1D array capable of storing various data types

In [7]:
import pandas as pd

x=[11,12,13,14]
var=pd.Series(x)
print(var)
print()

print(type(var))
print()

print(var[2])  # to ge the value int he index of 2
print()

0    11
1    12
2    13
3    14
dtype: int64

<class 'pandas.core.series.Series'>

13

In [8]:
import pandas as pd

x=[11,12,13,14]
var=pd.Series(x,index=["a","b","c","d"]) # cahnging the index
print(var)
print()

print(type(var))
print()

a    11
b    12
c    13
d    14
dtype: int64

<class 'pandas.core.series.Series'>

In [9]:
import pandas as pd

x=[11,12,13,14]
var=pd.Series(x,index=["a","b","c","d"],dtype="float") # To change the data type
print(var)
print()

print(type(var))
print()

a    11.0
b    12.0
c    13.0
d    14.0
dtype: float64

<class 'pandas.core.series.Series'>

In [10]:
import pandas as pd

x=[11,12,13,14]
var=pd.Series(x,index=["a","b","c","d"],dtype="float",name="Series_Data") # give the name to the dtype
print(var)
print()

print(type(var))
print()

a    11.0
b    12.0
c    13.0
d    14.0
Name: Series_Data, dtype: float64

<class 'pandas.core.series.Series'>

In [11]:
# dictionaries - are mutable (changeable) collections of unique key-value pairs
# defined with curly braces {} for mapping meaningful labels (keys) to data (values), like names to phone numbers.

dictionary ={"name":['Python','c','c++','java'],"property":[11,12,13,14],"rank":[1,3,2,4]}
var=pd.Series(dictionary)
var

name        [Python, c, c++, java]
property          [11, 12, 13, 14]
rank                  [1, 3, 2, 4]
dtype: object

In [12]:
dictionary ={"name":['Python','c','c++','java'],"property":[11,12,13,14],"rank":[1,3,2,4]}
var=pd.Series(dictionary)
print(var)

name        [Python, c, c++, java]
property          [11, 12, 13, 14]
rank                  [1, 3, 2, 4]
dtype: object

object data type because it has data types such as string,int

In [13]:
a=pd.Series(12)
print(a)
print(type(a))

0    12
dtype: int64
<class 'pandas.core.series.Series'>

In [14]:
a=pd.Series(12,index=[1,2,3,4,5,6,7])
print(a)
print(type(a))

1    12
2    12
3    12
4    12
5    12
6    12
7    12
dtype: int64
<class 'pandas.core.series.Series'>

In [15]:
a1=pd.Series(12,index=[1,2,3,4,5,6,7])
a2=pd.Series(12,index=[1,2,3,4,5])        # the boardcasting error will not come in pandas it will come
print(a1+a2)                              # NaN - not a number

1    24.0
2    24.0
3    24.0
4    24.0
5    24.0
6     NaN
7     NaN
dtype: float64

In [16]:
# dataframe in pandas
# 2D data structure

import pandas as pd

l=[1,2,3,4,5,6]          # can be done by list or dictionary

a=pd.DataFrame(l)
print(type(a))
print()
print(a)

<class 'pandas.core.frame.DataFrame'>

   0
0  1
1  2
2  3
3  4
4  5
5  6

In [17]:
dictionary={"a":[1,2,3,4,5],"b":[6,7,8,9,10]} # values or length must be

d=pd.DataFrame(dictionary,columns=["a"])  # to get one column
print(d)
print()

c=pd.DataFrame(dictionary)
print(c)
print()

print(dictionary["a"][1]) # get a perticular value

   a
0  1
1  2
2  3
3  4
4  5

   a   b
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

2

In [18]:
import pandas as pd

l=[[1,2,3,4,5],[6,7,8,9,10]]

a=pd.DataFrame(l)

print(type(a))
print(a)

<class 'pandas.core.frame.DataFrame'>
   0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

In [19]:
import pandas as pd
a={"s":pd.Series([1,2,3,4,5]),"r":pd.Series([11,12,13,14,15])} # Series inside the dictionary
b=pd.DataFrame(a)
print(b)
print(type(b))

   s   r
0  1  11
1  2  12
2  3  13
3  4  14
4  5  15
<class 'pandas.core.frame.DataFrame'>

In [20]:
# Aithmetic Operations in Python Pandas

import pandas as pd

a=pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})
a

   A  B
0  1  5
1  2  6
2  3  7
3  4  8

In [21]:
a["C"]=a["A"]/a["B"]
a

   A  B         C
0  1  5  0.200000
1  2  6  0.333333
2  3  7  0.428571
3  4  8  0.500000

In [22]:
a["C"]=a["A"]+a["B"]
a

   A  B   C
0  1  5   6
1  2  6   8
2  3  7  10
3  4  8  12

In [23]:
a["C"]=a["A"]%a["B"]
a

   A  B  C
0  1  5  1
1  2  6  2
2  3  7  3
3  4  8  4

In [24]:
a["C"]=a["A"]-a["B"]
a

   A  B  C
0  1  5 -4
1  2  6 -4
2  3  7 -4
3  4  8 -4

In [25]:
a["C"]=a["A"]*a["B"]
a

   A  B   C
0  1  5   5
1  2  6  12
2  3  7  21
3  4  8  32

In [26]:
var1=pd.DataFrame({"A":[10,20,30,40],"B":[50,60,40,20]})
var1

    A   B
0  10  50
1  20  60
2  30  40
3  40  20

In [27]:
var1["New"] = var1["A"] <=20
var1

    A   B    New
0  10  50   True
1  20  60   True
2  30  40  False
3  40  20  False

In [28]:
var1["New"] = var1["B"] <=20
var1["Alice"] = var1["B"] >=60
var1

    A   B    New  Alice
0  10  50  False  False
1  20  60  False   True
2  30  40  False  False
3  40  20   True  False

In [29]:
# Delete and Insert function in pandas

import pandas as pd

a= pd.DataFrame({"A":[10,20,30,40],"B":[50,60,70,80]})

a

a.insert (1,"c",a["A"])
a

    A   c   B
0  10  10  50
1  20  20  60
2  30  30  70
3  40  40  80

In [30]:
import pandas as pd

a= pd.DataFrame({"A":[10,20,30,40],"B":[50,60,70,80]})

a

a.insert (1,"c",[21,22,23,24])  # Passing list
a

    A   c   B
0  10  21  50
1  20  22  60
2  30  23  70
3  40  24  80

In [31]:
a["slicing"]=a["A"][:3]    # can use slicing method to get minimum numbered value
a

    A   c   B  slicing
0  10  21  50     10.0
1  20  22  60     20.0
2  30  23  70     30.0
3  40  24  80      NaN

In [32]:
# Delete function
# var.pop()

import pandas as pd

a= pd.DataFrame({"A":[10,20,30,40],"B":[50,60,70,80]})

a

a.pop("B") # to delete
a

    A
0  10
1  20
2  30
3  40

In [33]:
import pandas as pd

a= pd.DataFrame({"A":[10,20,30,40],"B":[50,60,70,80]})

a

a=a.pop("B") # to know what is deleted
a

0    50
1    60
2    70
3    80
Name: B, dtype: int64

In [34]:
# can delete using del function

import pandas as pd

a= pd.DataFrame({"A":[10,20,30,40],"B":[50,60,70,80]})
a

del a["A"]
a

    B
0  50
1  60
2  70
3  80

In [35]:
# CSV files in pandsa
# Comma Seperated values
# XL file format is an excel sheets binary file format which holds information about worksheets in a file
#to_csv()


import pandas as pd
dis={"a":[12,14,15,13,16],"b":[18,16,17,1,5],"c":[21,22,25,28,31]}  # Dictionary
a=pd.DataFrame(dis) # datframe

print(a)

a.to_csv("Test_new.csv")

    a   b   c
0  12  18  21
1  14  16  22
2  15  17  25
3  13   1  28
4  16   5  31

In [36]:
import os
os.listdir()

['.config', 'Test_new.csv', 'sample_data']

In [37]:
!ls

sample_data  Test_new.csv

In [38]:
import pandas as pd
dis={"a":[12,14,15,13,16],"b":[18,16,17,1,5],"c":[21,22,25,28,31]}  # Dictionary
a=pd.DataFrame(dis) # datframe

print(a)

a.to_csv("Test1_new.csv",index=False) # to remove the index value
# can change the header by     a.to_csv("Test1_new.csv",header=[m,n,p])

    a   b   c
0  12  18  21
1  14  16  22
2  15  17  25
3  13   1  28
4  16   5  31

In [39]:
from google.colab import files
uploaded = files.upload()

Saving sales_dataset.csv to sales_dataset.csv

In [40]:
import os
os.getcwd()

'/content'

In [41]:
os.listdir()

['.config',
 'Test_new.csv',
 'Test1_new.csv',
 'sales_dataset.csv',
 'sample_data']

In [42]:
from google.colab import files
files.upload()

Saving sales_dataset.csv to sales_dataset (1).csv

{'sales_dataset (1).csv': b'Date,Category,Product,Sales,Advertisement\r\n01-01-2023,Accessories,Belts,1407,28\r\n01-01-2023,Accessories,Gloves,2000,100\r\n,,,,\r\n01-01-2023,Accessories,Scarves,1679,84\r\n01-01-2023,Bottoms,Jeans,1096,22\r\n01-01-2023,Bottoms,Pants,1054,53\r\n01-01-2023,Bottoms,Skirts,1998,100\r\n01-01-2023,Dresses,Casual Dresses,1048,42\r\n01-01-2023,Dresses,Evening Gowns,1760,35\r\n01-01-2023,Footwear,Boots,1688,51\r\n01-01-2023,Footwear,Shoes,1127,45\r\n01-01-2023,Footwear,Sneakers,1311,39\r\n01-01-2023,Outerwear,Coats,1142,34\r\n01-01-2023,Outerwear,Jackets,1683,67\r\n01-01-2023,Outerwear,Sweaters,1370,41\r\n01-01-2023,Sleepwear,Nightgowns,1012,30\r\n01-01-2023,Sleepwear,Pajamas,1592,64\r\n01-01-2023,Sportswear,Sports Jerseys,1787,36\r\n01-01-2023,Sportswear,Yoga Pants,1666,33\r\n01-01-2023,Tops,Blouses,1331,40\r\n01-01-2023,Tops,Shirts,1693,68\r\n01-01-2023,Tops,T-shirts,1983,40\r\n02-01-2023,Accessories,Hats,1721,69\r\n02-01-2023,Accessories,Scarves,1695,51\r\n02-01-2023,Bottoms,Jeans,1154,23\r\n02-01-2023,Bottoms,Pants,1744,52\r\n02-01-2023,Bottoms,Skirts,1004,40\r\n02-01-2023,Dresses,Casual Dresses,1043,21\r\n02-01-2023,Dresses,Evening Gowns,1419,57\r\n02-01-2023,Footwear,Boots,1688,34\r\n02-01-2023,Footwear,Shoes,1791,72\r\n02-01-2023,Footwear,Sneakers,1789,54\r\n02-01-2023,Outerwear,Coats,1355,27\r\n02-01-2023,Outerwear,Jackets,1723,86\r\n02-01-2023,Outerwear,Sweaters,1048,21\r\n02-01-2023,Tops,Blouses,1911,96\r\n02-01-2023,Tops,Shirts,1492,75\r\n02-01-2023,Tops,T-shirts,1156,35\r\n03-01-2023,Accessories,Belts,1364,28\r\n03-01-2023,Accessories,Gloves,1556,60\r\n03-01-2023,Accessories,Hats,1245,30\r\n03-01-2023,Accessories,Scarves,1489,45\r\n03-01-2023,Bottoms,Jeans,1890,65\r\n03-01-2023,Bottoms,Pants,1321,48\r\n03-01-2023,Bottoms,Skirts,1543,70\r\n03-01-2023,Dresses,Casual Dresses,1586,55\r\n03-01-2023,Dresses,Evening Gowns,1924,75\r\n03-01-2023,Footwear,Boots,1720,58\r\n03-01-2023,Footwear,Shoes,1678,65\r\n03-01-2023,Footwear,Sneakers,1843,70\r\n03-01-2023,Outerwear,Coats,1475,60\r\n03-01-2023,Outerwear,Jackets,1810,90\r\n03-01-2023,Outerwear,Sweaters,1398,45\r\n03-01-2023,Sleepwear,Nightgowns,1189,32\r\n03-01-2023,Sleepwear,Pajamas,1634,55\r\n03-01-2023,Sportswear,Sports Jerseys,1865,78\r\n03-01-2023,Sportswear,Yoga Pants,1712,50\r\n03-01-2023,Tops,Blouses,1604,55\r\n03-01-2023,Tops,Shirts,1789,80\r\n03-01-2023,Tops,T-shirts,1423,50\r\n04-01-2023,Accessories,Belts,1438,33\r\n04-01-2023,Accessories,Gloves,1611,65\r\n04-01-2023,Accessories,Hats,1322,35\r\n04-01-2023,Accessories,Scarves,1567,52\r\n04-01-2023,Bottoms,Jeans,1945,75\r\n04-01-2023,Bottoms,Pants,1487,55\r\n04-01-2023,Bottoms,Skirts,1622,68\r\n04-01-2023,Dresses,Casual Dresses,1679,60\r\n04-01-2023,Dresses,Evening Gowns,1856,80\r\n04-01-2023,Footwear,Boots,1768,66\r\n04-01-2023,Footwear,Shoes,1733,70\r\n04-01-2023,Footwear,Sneakers,1895,82\r\n04-01-2023,Outerwear,Coats,1524,63\r\n04-01-2023,Outerwear,Jackets,1765,85\r\n04-01-2023,Outerwear,Sweaters,1411,47\r\n04-01-2023,Tops,Blouses,1702,58\r\n04-01-2023,Tops,Shirts,1648,60\r\n04-01-2023,Tops,T-shirts,1523,45\r\n'}

In [43]:
os.listdir()

['.config',
 'Test_new.csv',
 'Test1_new.csv',
 'sales_dataset (1).csv',
 'sales_dataset.csv',
 'sample_data']

In [44]:
'sales_dataset.csv'

'sales_dataset.csv'

In [45]:
import pandas as pd

df = pd.read_csv("sales_dataset.csv")
df.head()

         Date     Category  Product   Sales  Advertisement
0  01-01-2023  Accessories    Belts  1407.0           28.0
1  01-01-2023  Accessories   Gloves  2000.0          100.0
2         NaN          NaN      NaN     NaN            NaN
3  01-01-2023  Accessories  Scarves  1679.0           84.0
4  01-01-2023      Bottoms    Jeans  1096.0           22.0

In [46]:

# Read CSV files in pandas
# pandas read the data in a fast way

import pandas as pd

csv = pd.read_csv("sales_dataset.csv")    # IF in jupiter notebook or vs code can give path name of the file
csv

          Date     Category   Product   Sales  Advertisement
0   01-01-2023  Accessories     Belts  1407.0           28.0
1   01-01-2023  Accessories    Gloves  2000.0          100.0
2          NaN          NaN       NaN     NaN            NaN
3   01-01-2023  Accessories   Scarves  1679.0           84.0
4   01-01-2023      Bottoms     Jeans  1096.0           22.0
..         ...          ...       ...     ...            ...
73  04-01-2023    Outerwear   Jackets  1765.0           85.0
74  04-01-2023    Outerwear  Sweaters  1411.0           47.0
75  04-01-2023         Tops   Blouses  1702.0           58.0
76  04-01-2023         Tops    Shirts  1648.0           60.0
77  04-01-2023         Tops  T-shirts  1523.0           45.0

[78 rows x 5 columns]

In [47]:
# To get the perticular data or row

import pandas as pd

csv_1 = pd.read_csv("sales_dataset.csv",nrows=3)
csv_1

         Date     Category Product   Sales  Advertisement
0  01-01-2023  Accessories   Belts  1407.0           28.0
1  01-01-2023  Accessories  Gloves  2000.0          100.0
2         NaN          NaN     NaN     NaN            NaN

In [48]:
import pandas as pd
csv_1 = pd.read_csv("sales_dataset.csv",usecols=["Product","Category"],nrows=3)  # to get perticular column
csv_1

      Category Product
0  Accessories   Belts
1  Accessories  Gloves
2          NaN     NaN

In [49]:
# to skip the row data

import pandas as pd

csv_1 = pd.read_csv("sales_dataset.csv",usecols=["Product","Category"],nrows=3,skiprows=[2])  # to skip the row
csv_1

      Category  Product
0  Accessories    Belts
1          NaN      NaN
2  Accessories  Scarves

In [50]:
# to make an index

import pandas as pd

csv_1 = pd.read_csv("sales_dataset.csv",index_col="Date")  # date will become the index
csv_1

               Category   Product   Sales  Advertisement
Date
01-01-2023  Accessories     Belts  1407.0           28.0
01-01-2023  Accessories    Gloves  2000.0          100.0
NaN                 NaN       NaN     NaN            NaN
01-01-2023  Accessories   Scarves  1679.0           84.0
01-01-2023      Bottoms     Jeans  1096.0           22.0
...                 ...       ...     ...            ...
04-01-2023    Outerwear   Jackets  1765.0           85.0
04-01-2023    Outerwear  Sweaters  1411.0           47.0
04-01-2023         Tops   Blouses  1702.0           58.0
04-01-2023         Tops    Shirts  1648.0           60.0
04-01-2023         Tops  T-shirts  1523.0           45.0

[78 rows x 4 columns]

In [51]:
#Header parameter
# to make the heading
import pandas as pd

csv_1 = pd.read_csv("sales_dataset.csv",header=3)  # heading will be changed
csv_1

    Unnamed: 0   Unnamed: 1      Unnamed: 2  Unnamed: 3  Unnamed: 4
0   01-01-2023  Accessories         Scarves        1679          84
1   01-01-2023      Bottoms           Jeans        1096          22
2   01-01-2023      Bottoms           Pants        1054          53
3   01-01-2023      Bottoms          Skirts        1998         100
4   01-01-2023      Dresses  Casual Dresses        1048          42
..         ...          ...             ...         ...         ...
70  04-01-2023    Outerwear         Jackets        1765          85
71  04-01-2023    Outerwear        Sweaters        1411          47
72  04-01-2023         Tops         Blouses        1702          58
73  04-01-2023         Tops          Shirts        1648          60
74  04-01-2023         Tops        T-shirts        1523          45

[75 rows x 5 columns]

In [52]:
# Name parameter

# can use name parameter to make the heading
import pandas as pd

csv_1 = pd.read_csv("sales_dataset.csv",names=["1st col","2nd col","3rd col","4th col","5th col"])
csv_1

       1st col      2nd col   3rd col 4th col        5th col
0         Date     Category   Product   Sales  Advertisement
1   01-01-2023  Accessories     Belts    1407             28
2   01-01-2023  Accessories    Gloves    2000            100
3          NaN          NaN       NaN     NaN            NaN
4   01-01-2023  Accessories   Scarves    1679             84
..         ...          ...       ...     ...            ...
74  04-01-2023    Outerwear   Jackets    1765             85
75  04-01-2023    Outerwear  Sweaters    1411             47
76  04-01-2023         Tops   Blouses    1702             58
77  04-01-2023         Tops    Shirts    1648             60
78  04-01-2023         Tops  T-shirts    1523             45

[79 rows x 5 columns]

In [53]:
# Deleting the heading of the file and then creating a new heading by using prefix it gives the same name to every column

import pandas as pd

csv_1 = pd.read_csv("sales_dataset.csv", header=None)
csv_1

             0            1         2      3              4
0         Date     Category   Product  Sales  Advertisement
1   01-01-2023  Accessories     Belts   1407             28
2   01-01-2023  Accessories    Gloves   2000            100
3          NaN          NaN       NaN    NaN            NaN
4   01-01-2023  Accessories   Scarves   1679             84
..         ...          ...       ...    ...            ...
74  04-01-2023    Outerwear   Jackets   1765             85
75  04-01-2023    Outerwear  Sweaters   1411             47
76  04-01-2023         Tops   Blouses   1702             58
77  04-01-2023         Tops    Shirts   1648             60
78  04-01-2023         Tops  T-shirts   1523             45

[79 rows x 5 columns]

In [54]:

import pandas as pd

csv_1 = pd.read_csv("sales_dataset.csv", dtype={"Sales":"float"})  # converts sales data into float
csv_1

          Date     Category   Product   Sales  Advertisement
0   01-01-2023  Accessories     Belts  1407.0           28.0
1   01-01-2023  Accessories    Gloves  2000.0          100.0
2          NaN          NaN       NaN     NaN            NaN
3   01-01-2023  Accessories   Scarves  1679.0           84.0
4   01-01-2023      Bottoms     Jeans  1096.0           22.0
..         ...          ...       ...     ...            ...
73  04-01-2023    Outerwear   Jackets  1765.0           85.0
74  04-01-2023    Outerwear  Sweaters  1411.0           47.0
75  04-01-2023         Tops   Blouses  1702.0           58.0
76  04-01-2023         Tops    Shirts  1648.0           60.0
77  04-01-2023         Tops  T-shirts  1523.0           45.0

[78 rows x 5 columns]

In [55]:
# Pandas function

import pandas as pd
csv_1 = pd.read_csv("sales_dataset.csv")
csv_1

          Date     Category   Product   Sales  Advertisement
0   01-01-2023  Accessories     Belts  1407.0           28.0
1   01-01-2023  Accessories    Gloves  2000.0          100.0
2          NaN          NaN       NaN     NaN            NaN
3   01-01-2023  Accessories   Scarves  1679.0           84.0
4   01-01-2023      Bottoms     Jeans  1096.0           22.0
..         ...          ...       ...     ...            ...
73  04-01-2023    Outerwear   Jackets  1765.0           85.0
74  04-01-2023    Outerwear  Sweaters  1411.0           47.0
75  04-01-2023         Tops   Blouses  1702.0           58.0
76  04-01-2023         Tops    Shirts  1648.0           60.0
77  04-01-2023         Tops  T-shirts  1523.0           45.0

[78 rows x 5 columns]

In [56]:
csv_1.index

RangeIndex(start=0, stop=78, step=1)

In [57]:
csv_1.columns

Index(['Date', 'Category', 'Product', 'Sales', 'Advertisement'], dtype='object')

In [58]:
csv_1.describe()

             Sales  Advertisement
count    77.000000      77.000000
mean   1554.727273      54.909091
std     268.675143      19.690488
min    1004.000000      21.000000
25%    1370.000000      40.000000
50%    1611.000000      55.000000
75%    1744.000000      68.000000
max    2000.000000     100.000000

In [59]:
csv_1.head()  # shows the first five data

         Date     Category  Product   Sales  Advertisement
0  01-01-2023  Accessories    Belts  1407.0           28.0
1  01-01-2023  Accessories   Gloves  2000.0          100.0
2         NaN          NaN      NaN     NaN            NaN
3  01-01-2023  Accessories  Scarves  1679.0           84.0
4  01-01-2023      Bottoms    Jeans  1096.0           22.0

In [60]:
csv_1.head(4) # can give the data for the value given

         Date     Category  Product   Sales  Advertisement
0  01-01-2023  Accessories    Belts  1407.0           28.0
1  01-01-2023  Accessories   Gloves  2000.0          100.0
2         NaN          NaN      NaN     NaN            NaN
3  01-01-2023  Accessories  Scarves  1679.0           84.0

In [61]:
csv_1.tail() # gives data from the below

          Date   Category   Product   Sales  Advertisement
73  04-01-2023  Outerwear   Jackets  1765.0           85.0
74  04-01-2023  Outerwear  Sweaters  1411.0           47.0
75  04-01-2023       Tops   Blouses  1702.0           58.0
76  04-01-2023       Tops    Shirts  1648.0           60.0
77  04-01-2023       Tops  T-shirts  1523.0           45.0

In [62]:
csv_1.tail(10)

          Date   Category        Product   Sales  Advertisement
68  04-01-2023    Dresses  Evening Gowns  1856.0           80.0
69  04-01-2023   Footwear          Boots  1768.0           66.0
70  04-01-2023   Footwear          Shoes  1733.0           70.0
71  04-01-2023   Footwear       Sneakers  1895.0           82.0
72  04-01-2023  Outerwear          Coats  1524.0           63.0
73  04-01-2023  Outerwear        Jackets  1765.0           85.0
74  04-01-2023  Outerwear       Sweaters  1411.0           47.0
75  04-01-2023       Tops        Blouses  1702.0           58.0
76  04-01-2023       Tops         Shirts  1648.0           60.0
77  04-01-2023       Tops       T-shirts  1523.0           45.0

In [63]:
csv_1[:4] # to get number of rows and columns

         Date     Category  Product   Sales  Advertisement
0  01-01-2023  Accessories    Belts  1407.0           28.0
1  01-01-2023  Accessories   Gloves  2000.0          100.0
2         NaN          NaN      NaN     NaN            NaN
3  01-01-2023  Accessories  Scarves  1679.0           84.0

In [64]:
csv_1[2:4] # value form 2 to 3

         Date     Category  Product   Sales  Advertisement
2         NaN          NaN      NaN     NaN            NaN
3  01-01-2023  Accessories  Scarves  1679.0           84.0

In [65]:
print(type(csv_1))

<class 'pandas.core.frame.DataFrame'>

In [66]:
csv_1.index.array

<NumpyExtensionArray>
[ np.int64(0),  np.int64(1),  np.int64(2),  np.int64(3),  np.int64(4),
  np.int64(5),  np.int64(6),  np.int64(7),  np.int64(8),  np.int64(9),
 np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14),
 np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19),
 np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24),
 np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29),
 np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34),
 np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39),
 np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44),
 np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49),
 np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54),
 np.int64(55), np.int64(56), np.int64(57), np.int64(58), np.int64(59),
 np.int64(60), np.int64(61), np.int64(62), np.int64(63), np.int64(64),
 np.int64(65), np.int64(66), np.int64(67), np.int64(68), np.int64(69),
 np.int64(70), np.int64(71), np.int64(72), np.int64(73), np.int64(74),
 np.int64(75), np.int64(76), np.int64(77)]
Length: 78, dtype: int64

In [67]:
import numpy as np
a=np.array(csv_1)
a

array([['01-01-2023', 'Accessories', 'Belts', 1407.0, 28.0],
       ['01-01-2023', 'Accessories', 'Gloves', 2000.0, 100.0],
       [nan, nan, nan, nan, nan],
       ['01-01-2023', 'Accessories', 'Scarves', 1679.0, 84.0],
       ['01-01-2023', 'Bottoms', 'Jeans', 1096.0, 22.0],
       ['01-01-2023', 'Bottoms', 'Pants', 1054.0, 53.0],
       ['01-01-2023', 'Bottoms', 'Skirts', 1998.0, 100.0],
       ['01-01-2023', 'Dresses', 'Casual Dresses', 1048.0, 42.0],
       ['01-01-2023', 'Dresses', 'Evening Gowns', 1760.0, 35.0],
       ['01-01-2023', 'Footwear', 'Boots', 1688.0, 51.0],
       ['01-01-2023', 'Footwear', 'Shoes', 1127.0, 45.0],
       ['01-01-2023', 'Footwear', 'Sneakers', 1311.0, 39.0],
       ['01-01-2023', 'Outerwear', 'Coats', 1142.0, 34.0],
       ['01-01-2023', 'Outerwear', 'Jackets', 1683.0, 67.0],
       ['01-01-2023', 'Outerwear', 'Sweaters', 1370.0, 41.0],
       ['01-01-2023', 'Sleepwear', 'Nightgowns', 1012.0, 30.0],
       ['01-01-2023', 'Sleepwear', 'Pajamas', 1592.0, 64.0],
       ['01-01-2023', 'Sportswear', 'Sports Jerseys', 1787.0, 36.0],
       ['01-01-2023', 'Sportswear', 'Yoga Pants', 1666.0, 33.0],
       ['01-01-2023', 'Tops', 'Blouses', 1331.0, 40.0],
       ['01-01-2023', 'Tops', 'Shirts', 1693.0, 68.0],
       ['01-01-2023', 'Tops', 'T-shirts', 1983.0, 40.0],
       ['02-01-2023', 'Accessories', 'Hats', 1721.0, 69.0],
       ['02-01-2023', 'Accessories', 'Scarves', 1695.0, 51.0],
       ['02-01-2023', 'Bottoms', 'Jeans', 1154.0, 23.0],
       ['02-01-2023', 'Bottoms', 'Pants', 1744.0, 52.0],
       ['02-01-2023', 'Bottoms', 'Skirts', 1004.0, 40.0],
       ['02-01-2023', 'Dresses', 'Casual Dresses', 1043.0, 21.0],
       ['02-01-2023', 'Dresses', 'Evening Gowns', 1419.0, 57.0],
       ['02-01-2023', 'Footwear', 'Boots', 1688.0, 34.0],
       ['02-01-2023', 'Footwear', 'Shoes', 1791.0, 72.0],
       ['02-01-2023', 'Footwear', 'Sneakers', 1789.0, 54.0],
       ['02-01-2023', 'Outerwear', 'Coats', 1355.0, 27.0],
       ['02-01-2023', 'Outerwear', 'Jackets', 1723.0, 86.0],
       ['02-01-2023', 'Outerwear', 'Sweaters', 1048.0, 21.0],
       ['02-01-2023', 'Tops', 'Blouses', 1911.0, 96.0],
       ['02-01-2023', 'Tops', 'Shirts', 1492.0, 75.0],
       ['02-01-2023', 'Tops', 'T-shirts', 1156.0, 35.0],
       ['03-01-2023', 'Accessories', 'Belts', 1364.0, 28.0],
       ['03-01-2023', 'Accessories', 'Gloves', 1556.0, 60.0],
       ['03-01-2023', 'Accessories', 'Hats', 1245.0, 30.0],
       ['03-01-2023', 'Accessories', 'Scarves', 1489.0, 45.0],
       ['03-01-2023', 'Bottoms', 'Jeans', 1890.0, 65.0],
       ['03-01-2023', 'Bottoms', 'Pants', 1321.0, 48.0],
       ['03-01-2023', 'Bottoms', 'Skirts', 1543.0, 70.0],
       ['03-01-2023', 'Dresses', 'Casual Dresses', 1586.0, 55.0],
       ['03-01-2023', 'Dresses', 'Evening Gowns', 1924.0, 75.0],
       ['03-01-2023', 'Footwear', 'Boots', 1720.0, 58.0],
       ['03-01-2023', 'Footwear', 'Shoes', 1678.0, 65.0],
       ['03-01-2023', 'Footwear', 'Sneakers', 1843.0, 70.0],
       ['03-01-2023', 'Outerwear', 'Coats', 1475.0, 60.0],
       ['03-01-2023', 'Outerwear', 'Jackets', 1810.0, 90.0],
       ['03-01-2023', 'Outerwear', 'Sweaters', 1398.0, 45.0],
       ['03-01-2023', 'Sleepwear', 'Nightgowns', 1189.0, 32.0],
       ['03-01-2023', 'Sleepwear', 'Pajamas', 1634.0, 55.0],
       ['03-01-2023', 'Sportswear', 'Sports Jerseys', 1865.0, 78.0],
       ['03-01-2023', 'Sportswear', 'Yoga Pants', 1712.0, 50.0],
       ['03-01-2023', 'Tops', 'Blouses', 1604.0, 55.0],
       ['03-01-2023', 'Tops', 'Shirts', 1789.0, 80.0],
       ['03-01-2023', 'Tops', 'T-shirts', 1423.0, 50.0],
       ['04-01-2023', 'Accessories', 'Belts', 1438.0, 33.0],
       ['04-01-2023', 'Accessories', 'Gloves', 1611.0, 65.0],
       ['04-01-2023', 'Accessories', 'Hats', 1322.0, 35.0],
       ['04-01-2023', 'Accessories', 'Scarves', 1567.0, 52.0],
       ['04-01-2023', 'Bottoms', 'Jeans', 1945.0, 75.0],
       ['04-01-2023', 'Bottoms', 'Pants', 1487.0, 55.0],
       ['04-01-2023', 'Bottoms', 'Skirts', 1622.0, 68.0],
       ['04-01-2023', 'Dresses', 'Casual Dresses', 1679.0, 60.0],
       ['04-01-2023', 'Dresses', 'Evening Gowns', 1856.0, 80.0],
       ['04-01-2023', 'Footwear', 'Boots', 1768.0, 66.0],
       ['04-01-2023', 'Footwear', 'Shoes', 1733.0, 70.0],
       ['04-01-2023', 'Footwear', 'Sneakers', 1895.0, 82.0],
       ['04-01-2023', 'Outerwear', 'Coats', 1524.0, 63.0],
       ['04-01-2023', 'Outerwear', 'Jackets', 1765.0, 85.0],
       ['04-01-2023', 'Outerwear', 'Sweaters', 1411.0, 47.0],
       ['04-01-2023', 'Tops', 'Blouses', 1702.0, 58.0],
       ['04-01-2023', 'Tops', 'Shirts', 1648.0, 60.0],
       ['04-01-2023', 'Tops', 'T-shirts', 1523.0, 45.0]], dtype=object)

In [68]:
csv_1.sort_index(axis=0,ascending=False)

          Date     Category   Product   Sales  Advertisement
77  04-01-2023         Tops  T-shirts  1523.0           45.0
76  04-01-2023         Tops    Shirts  1648.0           60.0
75  04-01-2023         Tops   Blouses  1702.0           58.0
74  04-01-2023    Outerwear  Sweaters  1411.0           47.0
73  04-01-2023    Outerwear   Jackets  1765.0           85.0
..         ...          ...       ...     ...            ...
4   01-01-2023      Bottoms     Jeans  1096.0           22.0
3   01-01-2023  Accessories   Scarves  1679.0           84.0
2          NaN          NaN       NaN     NaN            NaN
1   01-01-2023  Accessories    Gloves  2000.0          100.0
0   01-01-2023  Accessories     Belts  1407.0           28.0

[78 rows x 5 columns]

In [69]:
csv_1.sort_index(axis=1,ascending=False)

     Sales   Product        Date     Category  Advertisement
0   1407.0     Belts  01-01-2023  Accessories           28.0
1   2000.0    Gloves  01-01-2023  Accessories          100.0
2      NaN       NaN         NaN          NaN            NaN
3   1679.0   Scarves  01-01-2023  Accessories           84.0
4   1096.0     Jeans  01-01-2023      Bottoms           22.0
..     ...       ...         ...          ...            ...
73  1765.0   Jackets  04-01-2023    Outerwear           85.0
74  1411.0  Sweaters  04-01-2023    Outerwear           47.0
75  1702.0   Blouses  04-01-2023         Tops           58.0
76  1648.0    Shirts  04-01-2023         Tops           60.0
77  1523.0  T-shirts  04-01-2023         Tops           45.0

[78 rows x 5 columns]

In [70]:
csv_1.loc[2,"Category"]="Skirt"
csv_1

          Date     Category   Product   Sales  Advertisement
0   01-01-2023  Accessories     Belts  1407.0           28.0
1   01-01-2023  Accessories    Gloves  2000.0          100.0
2          NaN        Skirt       NaN     NaN            NaN
3   01-01-2023  Accessories   Scarves  1679.0           84.0
4   01-01-2023      Bottoms     Jeans  1096.0           22.0
..         ...          ...       ...     ...            ...
73  04-01-2023    Outerwear   Jackets  1765.0           85.0
74  04-01-2023    Outerwear  Sweaters  1411.0           47.0
75  04-01-2023         Tops   Blouses  1702.0           58.0
76  04-01-2023         Tops    Shirts  1648.0           60.0
77  04-01-2023         Tops  T-shirts  1523.0           45.0

[78 rows x 5 columns]

In [71]:
csv_1.loc[1,"Category"]="BootCut"   # this is the correct method to use to change the data
csv_1

          Date     Category   Product   Sales  Advertisement
0   01-01-2023  Accessories     Belts  1407.0           28.0
1   01-01-2023      BootCut    Gloves  2000.0          100.0
2          NaN        Skirt       NaN     NaN            NaN
3   01-01-2023  Accessories   Scarves  1679.0           84.0
4   01-01-2023      Bottoms     Jeans  1096.0           22.0
..         ...          ...       ...     ...            ...
73  04-01-2023    Outerwear   Jackets  1765.0           85.0
74  04-01-2023    Outerwear  Sweaters  1411.0           47.0
75  04-01-2023         Tops   Blouses  1702.0           58.0
76  04-01-2023         Tops    Shirts  1648.0           60.0
77  04-01-2023         Tops  T-shirts  1523.0           45.0

[78 rows x 5 columns]

In [72]:
csv_1.loc[[0,2],["Category","Product"]]

      Category Product
0  Accessories   Belts
2        Skirt     NaN

In [73]:
csv_1.iloc[0,1]  # 0th index and 1st colulmn index

'Accessories'

In [74]:
# to drop the data

csv_1.drop("Category", axis=1) # delete the perticular given data

          Date   Product   Sales  Advertisement
0   01-01-2023     Belts  1407.0           28.0
1   01-01-2023    Gloves  2000.0          100.0
2          NaN       NaN     NaN            NaN
3   01-01-2023   Scarves  1679.0           84.0
4   01-01-2023     Jeans  1096.0           22.0
..         ...       ...     ...            ...
73  04-01-2023   Jackets  1765.0           85.0
74  04-01-2023  Sweaters  1411.0           47.0
75  04-01-2023   Blouses  1702.0           58.0
76  04-01-2023    Shirts  1648.0           60.0
77  04-01-2023  T-shirts  1523.0           45.0

[78 rows x 4 columns]

In [75]:
# Handling Missing value (dropna & fillna) in pandas
# To add or delete the data in a empty block

import pandas as pd
a = pd.read_csv("sales_dataset.csv")
a

a.dropna() # None value will be deleted.This will drop the row values

          Date     Category   Product   Sales  Advertisement
0   01-01-2023  Accessories     Belts  1407.0           28.0
1   01-01-2023  Accessories    Gloves  2000.0          100.0
3   01-01-2023  Accessories   Scarves  1679.0           84.0
4   01-01-2023      Bottoms     Jeans  1096.0           22.0
5   01-01-2023      Bottoms     Pants  1054.0           53.0
..         ...          ...       ...     ...            ...
73  04-01-2023    Outerwear   Jackets  1765.0           85.0
74  04-01-2023    Outerwear  Sweaters  1411.0           47.0
75  04-01-2023         Tops   Blouses  1702.0           58.0
76  04-01-2023         Tops    Shirts  1648.0           60.0
77  04-01-2023         Tops  T-shirts  1523.0           45.0

[77 rows x 5 columns]

In [76]:
a.dropna(axis=0)  # for column value

          Date     Category   Product   Sales  Advertisement
0   01-01-2023  Accessories     Belts  1407.0           28.0
1   01-01-2023  Accessories    Gloves  2000.0          100.0
3   01-01-2023  Accessories   Scarves  1679.0           84.0
4   01-01-2023      Bottoms     Jeans  1096.0           22.0
5   01-01-2023      Bottoms     Pants  1054.0           53.0
..         ...          ...       ...     ...            ...
73  04-01-2023    Outerwear   Jackets  1765.0           85.0
74  04-01-2023    Outerwear  Sweaters  1411.0           47.0
75  04-01-2023         Tops   Blouses  1702.0           58.0
76  04-01-2023         Tops    Shirts  1648.0           60.0
77  04-01-2023         Tops  T-shirts  1523.0           45.0

[77 rows x 5 columns]

In [77]:
from google.colab import files
uploaded = files.upload()

Saving sales.csv to sales.csv

In [78]:
import pandas as pd
a = pd.read_csv("sales.csv")
a

,order_id,order_date,region,sales_rep,product,category,units,unit_price,discount_pct,customer,gross_sales,discount_amt,net_sales
0,1001,03-01-2026,North,Asha,Notebook,Stationery,10.0,4.50,0.00,Acme Co,45.00,0.00,45.00
1,1002,04-01-2026,South,Ben,Pen,Stationery,25.0,1.20,0.05,Beta LLC,30.00,1.50,28.50
2,1003,06-01-2026,East,Chen,Desk Lamp,Office,3.0,18.99,0.10,Cedar Inc,56.97,5.70,51.27
3,1004,07-01-2026,West,Dia,Chair,Furniture,2.0,89.00,NaN,Delta Partners,178.00,0.00,178.00
4,1005,09-01-2026,North,Asha,Monitor,Electronics,1.0,159.99,0.08,Echo Corp,159.99,12.80,147.19
5,1006,11-01-2026,South,Ben,Keyboard,Electronics,4.0,24.50,0.00,NaN,98.00,0.00,98.00
6,1007,12-01-2026,East,Chen,Paper,Stationery,50.0,0.10,0.00,Foxtrot Ltd,5.00,0.00,5.00
7,1008,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
8,1009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1010,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.00,0.00,Ibis,55.00,0.00,55.00
10,1011,20-01-2026,East,Chen,Desk,Furniture,1.0,210.00,0.12,Juno,210.00,25.20,184.80
11,1012,22-01-2026,West,Dia,NaN,Office,7.0,3.25,0.00,Kilo,22.75,0.00,22.75

In [79]:
a.dropna() # removed all the NaN datavalues and row values

,order_id,order_date,region,sales_rep,product,category,units,unit_price,discount_pct,customer,gross_sales,discount_amt,net_sales
0,1001,03-01-2026,North,Asha,Notebook,Stationery,10.0,4.50,0.00,Acme Co,45.00,0.00,45.00
1,1002,04-01-2026,South,Ben,Pen,Stationery,25.0,1.20,0.05,Beta LLC,30.00,1.50,28.50
2,1003,06-01-2026,East,Chen,Desk Lamp,Office,3.0,18.99,0.10,Cedar Inc,56.97,5.70,51.27
4,1005,09-01-2026,North,Asha,Monitor,Electronics,1.0,159.99,0.08,Echo Corp,159.99,12.80,147.19
6,1007,12-01-2026,East,Chen,Paper,Stationery,50.0,0.10,0.00,Foxtrot Ltd,5.00,0.00,5.00
7,1008,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
9,1010,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.00,0.00,Ibis,55.00,0.00,55.00
10,1011,20-01-2026,East,Chen,Desk,Furniture,1.0,210.00,0.12,Juno,210.00,25.20,184.80

In [80]:
a.dropna(axis=1) # the NaN value in the column will be deleted .Whole coloumn will bw deleted

    order_id
0       1001
1       1002
2       1003
3       1004
4       1005
5       1006
6       1007
7       1008
8       1009
9       1010
10      1011
11      1012

In [81]:
# can use var.dropna(how="any") / var.dropna(how="all") for removing the rows and coumns of NaN data

In [82]:
import pandas as pd
a = pd.read_csv("sales.csv")
a

,order_id,order_date,region,sales_rep,product,category,units,unit_price,discount_pct,customer,gross_sales,discount_amt,net_sales
0,1001,03-01-2026,North,Asha,Notebook,Stationery,10.0,4.50,0.00,Acme Co,45.00,0.00,45.00
1,1002,04-01-2026,South,Ben,Pen,Stationery,25.0,1.20,0.05,Beta LLC,30.00,1.50,28.50
2,1003,06-01-2026,East,Chen,Desk Lamp,Office,3.0,18.99,0.10,Cedar Inc,56.97,5.70,51.27
3,1004,07-01-2026,West,Dia,Chair,Furniture,2.0,89.00,NaN,Delta Partners,178.00,0.00,178.00
4,1005,09-01-2026,North,Asha,Monitor,Electronics,1.0,159.99,0.08,Echo Corp,159.99,12.80,147.19
5,1006,11-01-2026,South,Ben,Keyboard,Electronics,4.0,24.50,0.00,NaN,98.00,0.00,98.00
6,1007,12-01-2026,East,Chen,Paper,Stationery,50.0,0.10,0.00,Foxtrot Ltd,5.00,0.00,5.00
7,1008,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
8,1009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1010,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.00,0.00,Ibis,55.00,0.00,55.00
10,1011,20-01-2026,East,Chen,Desk,Furniture,1.0,210.00,0.12,Juno,210.00,25.20,184.80
11,1012,22-01-2026,West,Dia,NaN,Office,7.0,3.25,0.00,Kilo,22.75,0.00,22.75

In [83]:
a.dropna(how="any") # delete all the emmpty block row

,order_id,order_date,region,sales_rep,product,category,units,unit_price,discount_pct,customer,gross_sales,discount_amt,net_sales
0,1001,03-01-2026,North,Asha,Notebook,Stationery,10.0,4.50,0.00,Acme Co,45.00,0.00,45.00
1,1002,04-01-2026,South,Ben,Pen,Stationery,25.0,1.20,0.05,Beta LLC,30.00,1.50,28.50
2,1003,06-01-2026,East,Chen,Desk Lamp,Office,3.0,18.99,0.10,Cedar Inc,56.97,5.70,51.27
4,1005,09-01-2026,North,Asha,Monitor,Electronics,1.0,159.99,0.08,Echo Corp,159.99,12.80,147.19
6,1007,12-01-2026,East,Chen,Paper,Stationery,50.0,0.10,0.00,Foxtrot Ltd,5.00,0.00,5.00
7,1008,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
9,1010,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.00,0.00,Ibis,55.00,0.00,55.00
10,1011,20-01-2026,East,Chen,Desk,Furniture,1.0,210.00,0.12,Juno,210.00,25.20,184.80

In [84]:
a.dropna(how="all") # deletes the value when whole row ill null only that row is deleted and other NaN values will be shown

,order_id,order_date,region,sales_rep,product,category,units,unit_price,discount_pct,customer,gross_sales,discount_amt,net_sales
0,1001,03-01-2026,North,Asha,Notebook,Stationery,10.0,4.50,0.00,Acme Co,45.00,0.00,45.00
1,1002,04-01-2026,South,Ben,Pen,Stationery,25.0,1.20,0.05,Beta LLC,30.00,1.50,28.50
2,1003,06-01-2026,East,Chen,Desk Lamp,Office,3.0,18.99,0.10,Cedar Inc,56.97,5.70,51.27
3,1004,07-01-2026,West,Dia,Chair,Furniture,2.0,89.00,NaN,Delta Partners,178.00,0.00,178.00
4,1005,09-01-2026,North,Asha,Monitor,Electronics,1.0,159.99,0.08,Echo Corp,159.99,12.80,147.19
5,1006,11-01-2026,South,Ben,Keyboard,Electronics,4.0,24.50,0.00,NaN,98.00,0.00,98.00
6,1007,12-01-2026,East,Chen,Paper,Stationery,50.0,0.10,0.00,Foxtrot Ltd,5.00,0.00,5.00
7,1008,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
8,1009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1010,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.00,0.00,Ibis,55.00,0.00,55.00
10,1011,20-01-2026,East,Chen,Desk,Furniture,1.0,210.00,0.12,Juno,210.00,25.20,184.80
11,1012,22-01-2026,West,Dia,NaN,Office,7.0,3.25,0.00,Kilo,22.75,0.00,22.75

In [85]:
# Subset Parameter  ( var.dropna(subset["column name"]))
# This parameter deletes the given column name, NaN bolck row will be deleted


a.dropna(subset=["customer"])

,order_id,order_date,region,sales_rep,product,category,units,unit_price,discount_pct,customer,gross_sales,discount_amt,net_sales
0,1001,03-01-2026,North,Asha,Notebook,Stationery,10.0,4.50,0.00,Acme Co,45.00,0.00,45.00
1,1002,04-01-2026,South,Ben,Pen,Stationery,25.0,1.20,0.05,Beta LLC,30.00,1.50,28.50
2,1003,06-01-2026,East,Chen,Desk Lamp,Office,3.0,18.99,0.10,Cedar Inc,56.97,5.70,51.27
3,1004,07-01-2026,West,Dia,Chair,Furniture,2.0,89.00,NaN,Delta Partners,178.00,0.00,178.00
4,1005,09-01-2026,North,Asha,Monitor,Electronics,1.0,159.99,0.08,Echo Corp,159.99,12.80,147.19
6,1007,12-01-2026,East,Chen,Paper,Stationery,50.0,0.10,0.00,Foxtrot Ltd,5.00,0.00,5.00
7,1008,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
9,1010,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.00,0.00,Ibis,55.00,0.00,55.00
10,1011,20-01-2026,East,Chen,Desk,Furniture,1.0,210.00,0.12,Juno,210.00,25.20,184.80
11,1012,22-01-2026,West,Dia,NaN,Office,7.0,3.25,0.00,Kilo,22.75,0.00,22.75

In [86]:
# inplace parameter(  var.dropna(inplace=True))
# It will removes the NaN block
# inplace=True → change the original DataFrame itself
# inplace=False (default) → create and return a new DataFrame
a.dropna(inplace=True)
a

,order_id,order_date,region,sales_rep,product,category,units,unit_price,discount_pct,customer,gross_sales,discount_amt,net_sales
0,1001,03-01-2026,North,Asha,Notebook,Stationery,10.0,4.50,0.00,Acme Co,45.00,0.00,45.00
1,1002,04-01-2026,South,Ben,Pen,Stationery,25.0,1.20,0.05,Beta LLC,30.00,1.50,28.50
2,1003,06-01-2026,East,Chen,Desk Lamp,Office,3.0,18.99,0.10,Cedar Inc,56.97,5.70,51.27
4,1005,09-01-2026,North,Asha,Monitor,Electronics,1.0,159.99,0.08,Echo Corp,159.99,12.80,147.19
6,1007,12-01-2026,East,Chen,Paper,Stationery,50.0,0.10,0.00,Foxtrot Ltd,5.00,0.00,5.00
7,1008,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
9,1010,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.00,0.00,Ibis,55.00,0.00,55.00
10,1011,20-01-2026,East,Chen,Desk,Furniture,1.0,210.00,0.12,Juno,210.00,25.20,184.80

In [87]:
# thresh parameter ( var.dropna(tresh="number of null values" ))
# this will reomve the row which is having given number of NaN

a.dropna(thresh=1)

,order_id,order_date,region,sales_rep,product,category,units,unit_price,discount_pct,customer,gross_sales,discount_amt,net_sales
0,1001,03-01-2026,North,Asha,Notebook,Stationery,10.0,4.50,0.00,Acme Co,45.00,0.00,45.00
1,1002,04-01-2026,South,Ben,Pen,Stationery,25.0,1.20,0.05,Beta LLC,30.00,1.50,28.50
2,1003,06-01-2026,East,Chen,Desk Lamp,Office,3.0,18.99,0.10,Cedar Inc,56.97,5.70,51.27
4,1005,09-01-2026,North,Asha,Monitor,Electronics,1.0,159.99,0.08,Echo Corp,159.99,12.80,147.19
6,1007,12-01-2026,East,Chen,Paper,Stationery,50.0,0.10,0.00,Foxtrot Ltd,5.00,0.00,5.00
7,1008,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
9,1010,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.00,0.00,Ibis,55.00,0.00,55.00
10,1011,20-01-2026,East,Chen,Desk,Furniture,1.0,210.00,0.12,Juno,210.00,25.20,184.80

In [88]:
# fillna
# used to fill the values

In [89]:
from google.colab import files
uploaded = files.upload()

Saving sales.csv to sales (1).csv

In [90]:
import pandas as pd
a = pd.read_csv("sales.csv")
a

,order_id,order_date,region,sales_rep,product,category,units,unit_price,discount_pct,customer,gross_sales,discount_amt,net_sales
0,1001,03-01-2026,North,Asha,Notebook,Stationery,10.0,4.50,0.00,Acme Co,45.00,0.00,45.00
1,1002,04-01-2026,South,Ben,Pen,Stationery,25.0,1.20,0.05,Beta LLC,30.00,1.50,28.50
2,1003,06-01-2026,East,Chen,Desk Lamp,Office,3.0,18.99,0.10,Cedar Inc,56.97,5.70,51.27
3,1004,07-01-2026,West,Dia,Chair,Furniture,2.0,89.00,NaN,Delta Partners,178.00,0.00,178.00
4,1005,09-01-2026,North,Asha,Monitor,Electronics,1.0,159.99,0.08,Echo Corp,159.99,12.80,147.19
5,1006,11-01-2026,South,Ben,Keyboard,Electronics,4.0,24.50,0.00,NaN,98.00,0.00,98.00
6,1007,12-01-2026,East,Chen,Paper,Stationery,50.0,0.10,0.00,Foxtrot Ltd,5.00,0.00,5.00
7,1008,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
8,1009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1010,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.00,0.00,Ibis,55.00,0.00,55.00
10,1011,20-01-2026,East,Chen,Desk,Furniture,1.0,210.00,0.12,Juno,210.00,25.20,184.80
11,1012,22-01-2026,West,Dia,NaN,Office,7.0,3.25,0.00,Kilo,22.75,0.00,22.75

In [91]:
a.fillna("valuse to be added")

,order_id,order_date,region,sales_rep,product,category,units,unit_price,discount_pct,customer,gross_sales,discount_amt,net_sales
0,1001,03-01-2026,North,Asha,Notebook,Stationery,10.0,4.5,0.0,Acme Co,45.0,0.0,45.0
1,1002,04-01-2026,South,Ben,Pen,Stationery,25.0,1.2,0.05,Beta LLC,30.0,1.5,28.5
2,1003,06-01-2026,East,Chen,Desk Lamp,Office,3.0,18.99,0.1,Cedar Inc,56.97,5.7,51.27
3,1004,07-01-2026,West,Dia,Chair,Furniture,2.0,89.0,valuse to be added,Delta Partners,178.0,0.0,178.0
4,1005,09-01-2026,North,Asha,Monitor,Electronics,1.0,159.99,0.08,Echo Corp,159.99,12.8,147.19
5,1006,11-01-2026,South,Ben,Keyboard,Electronics,4.0,24.5,0.0,valuse to be added,98.0,0.0,98.0
6,1007,12-01-2026,East,Chen,Paper,Stationery,50.0,0.1,0.0,Foxtrot Ltd,5.0,0.0,5.0
7,1008,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
8,1009,valuse to be added,valuse to be added,valuse to be added,valuse to be added,valuse to be added,valuse to be added,valuse to be added,valuse to be added,valuse to be added,valuse to be added,valuse to be added,valuse to be added
9,1010,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.0,0.0,Ibis,55.0,0.0,55.0
10,1011,20-01-2026,East,Chen,Desk,Furniture,1.0,210.0,0.12,Juno,210.0,25.2,184.8
11,1012,22-01-2026,West,Dia,valuse to be added,Office,7.0,3.25,0.0,Kilo,22.75,0.0,22.75

In [92]:
a.fillna({"order_date":"date to be added","product":"product to be added"}) # creating dictionary to fill the pericular null bolck

,order_id,order_date,region,sales_rep,product,category,units,unit_price,discount_pct,customer,gross_sales,discount_amt,net_sales
0,1001,03-01-2026,North,Asha,Notebook,Stationery,10.0,4.50,0.00,Acme Co,45.00,0.00,45.00
1,1002,04-01-2026,South,Ben,Pen,Stationery,25.0,1.20,0.05,Beta LLC,30.00,1.50,28.50
2,1003,06-01-2026,East,Chen,Desk Lamp,Office,3.0,18.99,0.10,Cedar Inc,56.97,5.70,51.27
3,1004,07-01-2026,West,Dia,Chair,Furniture,2.0,89.00,NaN,Delta Partners,178.00,0.00,178.00
4,1005,09-01-2026,North,Asha,Monitor,Electronics,1.0,159.99,0.08,Echo Corp,159.99,12.80,147.19
5,1006,11-01-2026,South,Ben,Keyboard,Electronics,4.0,24.50,0.00,NaN,98.00,0.00,98.00
6,1007,12-01-2026,East,Chen,Paper,Stationery,50.0,0.10,0.00,Foxtrot Ltd,5.00,0.00,5.00
7,1008,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
8,1009,date to be added,NaN,NaN,product to be added,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1010,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.00,0.00,Ibis,55.00,0.00,55.00
10,1011,20-01-2026,East,Chen,Desk,Furniture,1.0,210.00,0.12,Juno,210.00,25.20,184.80
11,1012,22-01-2026,West,Dia,product to be added,Office,7.0,3.25,0.00,Kilo,22.75,0.00,22.75

In [93]:
a.fillna(method="ffill") # forwardfill
# fill the empty block by previous data

/tmp/ipython-input-496417244.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  a.fillna(method="ffill") # forwardfill

,order_id,order_date,region,sales_rep,product,category,units,unit_price,discount_pct,customer,gross_sales,discount_amt,net_sales
0,1001,03-01-2026,North,Asha,Notebook,Stationery,10.0,4.50,0.00,Acme Co,45.00,0.00,45.00
1,1002,04-01-2026,South,Ben,Pen,Stationery,25.0,1.20,0.05,Beta LLC,30.00,1.50,28.50
2,1003,06-01-2026,East,Chen,Desk Lamp,Office,3.0,18.99,0.10,Cedar Inc,56.97,5.70,51.27
3,1004,07-01-2026,West,Dia,Chair,Furniture,2.0,89.00,0.10,Delta Partners,178.00,0.00,178.00
4,1005,09-01-2026,North,Asha,Monitor,Electronics,1.0,159.99,0.08,Echo Corp,159.99,12.80,147.19
5,1006,11-01-2026,South,Ben,Keyboard,Electronics,4.0,24.50,0.00,Echo Corp,98.00,0.00,98.00
6,1007,12-01-2026,East,Chen,Paper,Stationery,50.0,0.10,0.00,Foxtrot Ltd,5.00,0.00,5.00
7,1008,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
8,1009,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
9,1010,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.00,0.00,Ibis,55.00,0.00,55.00
10,1011,20-01-2026,East,Chen,Desk,Furniture,1.0,210.00,0.12,Juno,210.00,25.20,184.80
11,1012,22-01-2026,West,Dia,Desk,Office,7.0,3.25,0.00,Kilo,22.75,0.00,22.75

In [94]:
a.ffill()

,order_id,order_date,region,sales_rep,product,category,units,unit_price,discount_pct,customer,gross_sales,discount_amt,net_sales
0,1001,03-01-2026,North,Asha,Notebook,Stationery,10.0,4.50,0.00,Acme Co,45.00,0.00,45.00
1,1002,04-01-2026,South,Ben,Pen,Stationery,25.0,1.20,0.05,Beta LLC,30.00,1.50,28.50
2,1003,06-01-2026,East,Chen,Desk Lamp,Office,3.0,18.99,0.10,Cedar Inc,56.97,5.70,51.27
3,1004,07-01-2026,West,Dia,Chair,Furniture,2.0,89.00,0.10,Delta Partners,178.00,0.00,178.00
4,1005,09-01-2026,North,Asha,Monitor,Electronics,1.0,159.99,0.08,Echo Corp,159.99,12.80,147.19
5,1006,11-01-2026,South,Ben,Keyboard,Electronics,4.0,24.50,0.00,Echo Corp,98.00,0.00,98.00
6,1007,12-01-2026,East,Chen,Paper,Stationery,50.0,0.10,0.00,Foxtrot Ltd,5.00,0.00,5.00
7,1008,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
8,1009,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
9,1010,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.00,0.00,Ibis,55.00,0.00,55.00
10,1011,20-01-2026,East,Chen,Desk,Furniture,1.0,210.00,0.12,Juno,210.00,25.20,184.80
11,1012,22-01-2026,West,Dia,Desk,Office,7.0,3.25,0.00,Kilo,22.75,0.00,22.75

In [95]:
a.fillna(method="bfill") # backwardfill
# fill the empty block by next data

/tmp/ipython-input-1352020882.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  a.fillna(method="bfill") # backwardfill

,order_id,order_date,region,sales_rep,product,category,units,unit_price,discount_pct,customer,gross_sales,discount_amt,net_sales
0,1001,03-01-2026,North,Asha,Notebook,Stationery,10.0,4.50,0.00,Acme Co,45.00,0.00,45.00
1,1002,04-01-2026,South,Ben,Pen,Stationery,25.0,1.20,0.05,Beta LLC,30.00,1.50,28.50
2,1003,06-01-2026,East,Chen,Desk Lamp,Office,3.0,18.99,0.10,Cedar Inc,56.97,5.70,51.27
3,1004,07-01-2026,West,Dia,Chair,Furniture,2.0,89.00,0.08,Delta Partners,178.00,0.00,178.00
4,1005,09-01-2026,North,Asha,Monitor,Electronics,1.0,159.99,0.08,Echo Corp,159.99,12.80,147.19
5,1006,11-01-2026,South,Ben,Keyboard,Electronics,4.0,24.50,0.00,Foxtrot Ltd,98.00,0.00,98.00
6,1007,12-01-2026,East,Chen,Paper,Stationery,50.0,0.10,0.00,Foxtrot Ltd,5.00,0.00,5.00
7,1008,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
8,1009,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.00,0.00,Ibis,55.00,0.00,55.00
9,1010,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.00,0.00,Ibis,55.00,0.00,55.00
10,1011,20-01-2026,East,Chen,Desk,Furniture,1.0,210.00,0.12,Juno,210.00,25.20,184.80
11,1012,22-01-2026,West,Dia,NaN,Office,7.0,3.25,0.00,Kilo,22.75,0.00,22.75

In [96]:
a.ffill(axis=0)

,order_id,order_date,region,sales_rep,product,category,units,unit_price,discount_pct,customer,gross_sales,discount_amt,net_sales
0,1001,03-01-2026,North,Asha,Notebook,Stationery,10.0,4.50,0.00,Acme Co,45.00,0.00,45.00
1,1002,04-01-2026,South,Ben,Pen,Stationery,25.0,1.20,0.05,Beta LLC,30.00,1.50,28.50
2,1003,06-01-2026,East,Chen,Desk Lamp,Office,3.0,18.99,0.10,Cedar Inc,56.97,5.70,51.27
3,1004,07-01-2026,West,Dia,Chair,Furniture,2.0,89.00,0.10,Delta Partners,178.00,0.00,178.00
4,1005,09-01-2026,North,Asha,Monitor,Electronics,1.0,159.99,0.08,Echo Corp,159.99,12.80,147.19
5,1006,11-01-2026,South,Ben,Keyboard,Electronics,4.0,24.50,0.00,Echo Corp,98.00,0.00,98.00
6,1007,12-01-2026,East,Chen,Paper,Stationery,50.0,0.10,0.00,Foxtrot Ltd,5.00,0.00,5.00
7,1008,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
8,1009,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
9,1010,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.00,0.00,Ibis,55.00,0.00,55.00
10,1011,20-01-2026,East,Chen,Desk,Furniture,1.0,210.00,0.12,Juno,210.00,25.20,184.80
11,1012,22-01-2026,West,Dia,Desk,Office,7.0,3.25,0.00,Kilo,22.75,0.00,22.75

In [97]:
a.ffill(axis=1)  # Pandas fills missing values row-wise (left → right)

/tmp/ipython-input-1505985848.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  a.ffill(axis=1)  # Pandas fills missing values row-wise (left → right)

,order_id,order_date,region,sales_rep,product,category,units,unit_price,discount_pct,customer,gross_sales,discount_amt,net_sales
0,1001,03-01-2026,North,Asha,Notebook,Stationery,10.0,4.5,0.0,Acme Co,45.0,0.0,45.0
1,1002,04-01-2026,South,Ben,Pen,Stationery,25.0,1.2,0.05,Beta LLC,30.0,1.5,28.5
2,1003,06-01-2026,East,Chen,Desk Lamp,Office,3.0,18.99,0.1,Cedar Inc,56.97,5.7,51.27
3,1004,07-01-2026,West,Dia,Chair,Furniture,2.0,89.0,89.0,Delta Partners,178.0,0.0,178.0
4,1005,09-01-2026,North,Asha,Monitor,Electronics,1.0,159.99,0.08,Echo Corp,159.99,12.8,147.19
5,1006,11-01-2026,South,Ben,Keyboard,Electronics,4.0,24.5,0.0,0.0,98.0,0.0,98.0
6,1007,12-01-2026,East,Chen,Paper,Stationery,50.0,0.1,0.0,Foxtrot Ltd,5.0,0.0,5.0
7,1008,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
8,1009,1009,1009,1009,1009,1009,1009,1009,1009,1009,1009,1009,1009
9,1010,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.0,0.0,Ibis,55.0,0.0,55.0
10,1011,20-01-2026,East,Chen,Desk,Furniture,1.0,210.0,0.12,Juno,210.0,25.2,184.8
11,1012,22-01-2026,West,Dia,Dia,Office,7.0,3.25,0.0,Kilo,22.75,0.0,22.75

In [98]:
a.fillna(12,inplace=True)
a

,order_id,order_date,region,sales_rep,product,category,units,unit_price,discount_pct,customer,gross_sales,discount_amt,net_sales
0,1001,03-01-2026,North,Asha,Notebook,Stationery,10.0,4.50,0.00,Acme Co,45.00,0.00,45.00
1,1002,04-01-2026,South,Ben,Pen,Stationery,25.0,1.20,0.05,Beta LLC,30.00,1.50,28.50
2,1003,06-01-2026,East,Chen,Desk Lamp,Office,3.0,18.99,0.10,Cedar Inc,56.97,5.70,51.27
3,1004,07-01-2026,West,Dia,Chair,Furniture,2.0,89.00,12.00,Delta Partners,178.00,0.00,178.00
4,1005,09-01-2026,North,Asha,Monitor,Electronics,1.0,159.99,0.08,Echo Corp,159.99,12.80,147.19
5,1006,11-01-2026,South,Ben,Keyboard,Electronics,4.0,24.50,0.00,12,98.00,0.00,98.00
6,1007,12-01-2026,East,Chen,Paper,Stationery,50.0,0.10,0.00,Foxtrot Ltd,5.00,0.00,5.00
7,1008,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
8,1009,12,12,12,12,12,12.0,12.00,12.00,12,12.00,12.00,12.00
9,1010,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.00,0.00,Ibis,55.00,0.00,55.00
10,1011,20-01-2026,East,Chen,Desk,Furniture,1.0,210.00,0.12,Juno,210.00,25.20,184.80
11,1012,22-01-2026,West,Dia,12,Office,7.0,3.25,0.00,Kilo,22.75,0.00,22.75

In [99]:
from google.colab import files
uploaded = files.upload()

Saving sales.csv to sales (2).csv

In [100]:
import pandas as pd
a = pd.read_csv("sales.csv")

In [101]:
#limit parameter
a.fillna("Python",limit = 1) # in the column one NaN block will be filled by given input

,order_id,order_date,region,sales_rep,product,category,units,unit_price,discount_pct,customer,gross_sales,discount_amt,net_sales
0,1001,03-01-2026,North,Asha,Notebook,Stationery,10.0,4.5,0.0,Acme Co,45.0,0.0,45.0
1,1002,04-01-2026,South,Ben,Pen,Stationery,25.0,1.2,0.05,Beta LLC,30.0,1.5,28.5
2,1003,06-01-2026,East,Chen,Desk Lamp,Office,3.0,18.99,0.1,Cedar Inc,56.97,5.7,51.27
3,1004,07-01-2026,West,Dia,Chair,Furniture,2.0,89.0,Python,Delta Partners,178.0,0.0,178.0
4,1005,09-01-2026,North,Asha,Monitor,Electronics,1.0,159.99,0.08,Echo Corp,159.99,12.8,147.19
5,1006,11-01-2026,South,Ben,Keyboard,Electronics,4.0,24.5,0.0,Python,98.0,0.0,98.0
6,1007,12-01-2026,East,Chen,Paper,Stationery,50.0,0.1,0.0,Foxtrot Ltd,5.0,0.0,5.0
7,1008,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
8,1009,Python,Python,Python,Python,Python,Python,Python,NaN,NaN,Python,Python,Python
9,1010,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.0,0.0,Ibis,55.0,0.0,55.0
10,1011,20-01-2026,East,Chen,Desk,Furniture,1.0,210.0,0.12,Juno,210.0,25.2,184.8
11,1012,22-01-2026,West,Dia,NaN,Office,7.0,3.25,0.0,Kilo,22.75,0.0,22.75

In [102]:
# Handling missing values (Replace and Interpolate in pandas)

In [103]:
# Replace

import pandas as pd
a=pd.read_csv("sales.csv")

In [104]:
a.replace(to_replace=1,value=100)   # 1 will be replaced by the given value

,order_id,order_date,region,sales_rep,product,category,units,unit_price,discount_pct,customer,gross_sales,discount_amt,net_sales
0,1001,03-01-2026,North,Asha,Notebook,Stationery,10.0,4.50,0.00,Acme Co,45.00,0.00,45.00
1,1002,04-01-2026,South,Ben,Pen,Stationery,25.0,1.20,0.05,Beta LLC,30.00,1.50,28.50
2,1003,06-01-2026,East,Chen,Desk Lamp,Office,3.0,18.99,0.10,Cedar Inc,56.97,5.70,51.27
3,1004,07-01-2026,West,Dia,Chair,Furniture,2.0,89.00,NaN,Delta Partners,178.00,0.00,178.00
4,1005,09-01-2026,North,Asha,Monitor,Electronics,100.0,159.99,0.08,Echo Corp,159.99,12.80,147.19
5,1006,11-01-2026,South,Ben,Keyboard,Electronics,4.0,24.50,0.00,NaN,98.00,0.00,98.00
6,1007,12-01-2026,East,Chen,Paper,Stationery,50.0,0.10,0.00,Foxtrot Ltd,5.00,0.00,5.00
7,1008,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
8,1009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1010,18-01-2026,South,Ben,Whiteboard,Office,100.0,55.00,0.00,Ibis,55.00,0.00,55.00
10,1011,20-01-2026,East,Chen,Desk,Furniture,100.0,210.00,0.12,Juno,210.00,25.20,184.80
11,1012,22-01-2026,West,Dia,NaN,Office,7.0,3.25,0.00,Kilo,22.75,0.00,22.75

In [105]:
a.replace(to_replace="Asha",value="Nishmitha")

,order_id,order_date,region,sales_rep,product,category,units,unit_price,discount_pct,customer,gross_sales,discount_amt,net_sales
0,1001,03-01-2026,North,Nishmitha,Notebook,Stationery,10.0,4.50,0.00,Acme Co,45.00,0.00,45.00
1,1002,04-01-2026,South,Ben,Pen,Stationery,25.0,1.20,0.05,Beta LLC,30.00,1.50,28.50
2,1003,06-01-2026,East,Chen,Desk Lamp,Office,3.0,18.99,0.10,Cedar Inc,56.97,5.70,51.27
3,1004,07-01-2026,West,Dia,Chair,Furniture,2.0,89.00,NaN,Delta Partners,178.00,0.00,178.00
4,1005,09-01-2026,North,Nishmitha,Monitor,Electronics,1.0,159.99,0.08,Echo Corp,159.99,12.80,147.19
5,1006,11-01-2026,South,Ben,Keyboard,Electronics,4.0,24.50,0.00,NaN,98.00,0.00,98.00
6,1007,12-01-2026,East,Chen,Paper,Stationery,50.0,0.10,0.00,Foxtrot Ltd,5.00,0.00,5.00
7,1008,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
8,1009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1010,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.00,0.00,Ibis,55.00,0.00,55.00
10,1011,20-01-2026,East,Chen,Desk,Furniture,1.0,210.00,0.12,Juno,210.00,25.20,184.80
11,1012,22-01-2026,West,Dia,NaN,Office,7.0,3.25,0.00,Kilo,22.75,0.00,22.75

In [106]:
a.replace([1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012],[1,2,3,4,5,6,7,8,9,10,11,12])

,order_id,order_date,region,sales_rep,product,category,units,unit_price,discount_pct,customer,gross_sales,discount_amt,net_sales
0,1,03-01-2026,North,Asha,Notebook,Stationery,10.0,4.50,0.00,Acme Co,45.00,0.00,45.00
1,2,04-01-2026,South,Ben,Pen,Stationery,25.0,1.20,0.05,Beta LLC,30.00,1.50,28.50
2,3,06-01-2026,East,Chen,Desk Lamp,Office,3.0,18.99,0.10,Cedar Inc,56.97,5.70,51.27
3,4,07-01-2026,West,Dia,Chair,Furniture,2.0,89.00,NaN,Delta Partners,178.00,0.00,178.00
4,5,09-01-2026,North,Asha,Monitor,Electronics,1.0,159.99,0.08,Echo Corp,159.99,12.80,147.19
5,6,11-01-2026,South,Ben,Keyboard,Electronics,4.0,24.50,0.00,NaN,98.00,0.00,98.00
6,7,12-01-2026,East,Chen,Paper,Stationery,50.0,0.10,0.00,Foxtrot Ltd,5.00,0.00,5.00
7,8,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
8,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.00,0.00,Ibis,55.00,0.00,55.00
10,11,20-01-2026,East,Chen,Desk,Furniture,1.0,210.00,0.12,Juno,210.00,25.20,184.80
11,12,22-01-2026,West,Dia,NaN,Office,7.0,3.25,0.00,Kilo,22.75,0.00,22.75

In [107]:
a.replace("[A-Za-z]","ha",regex=True) # all the alphabetic characters will be replaced by ha by using regex

,order_id,order_date,region,sales_rep,product,category,units,unit_price,discount_pct,customer,gross_sales,discount_amt,net_sales
0,1001,03-01-2026,hahahahaha,hahahaha,hahahahahahahaha,hahahahahahahahahaha,10.0,4.50,0.00,hahahaha haha,45.00,0.00,45.00
1,1002,04-01-2026,hahahahaha,hahaha,hahaha,hahahahahahahahahaha,25.0,1.20,0.05,hahahaha hahaha,30.00,1.50,28.50
2,1003,06-01-2026,hahahaha,hahahaha,hahahaha hahahaha,hahahahahaha,3.0,18.99,0.10,hahahahaha hahaha,56.97,5.70,51.27
3,1004,07-01-2026,hahahaha,hahaha,hahahahaha,hahahahahahahahaha,2.0,89.00,NaN,hahahahaha hahahahahahahaha,178.00,0.00,178.00
4,1005,09-01-2026,hahahahaha,hahahaha,hahahahahahaha,hahahahahahahahahahaha,1.0,159.99,0.08,hahahaha hahahaha,159.99,12.80,147.19
5,1006,11-01-2026,hahahahaha,hahaha,hahahahahahahaha,hahahahahahahahahahaha,4.0,24.50,0.00,NaN,98.00,0.00,98.00
6,1007,12-01-2026,hahahaha,hahahaha,hahahahaha,hahahahahahahahahaha,50.0,0.10,0.00,hahahahahahaha hahaha,5.00,0.00,5.00
7,1008,14-01-2026,hahahaha,hahaha,hahahahahahaha,hahahahahaha,5.0,6.75,0.15,hahahahaha hahahahaha,33.75,5.06,28.69
8,1009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1010,18-01-2026,hahahahaha,hahaha,hahahahahahahahahaha,hahahahahaha,1.0,55.00,0.00,hahahaha,55.00,0.00,55.00
10,1011,20-01-2026,hahahaha,hahahaha,hahahaha,hahahahahahahahaha,1.0,210.00,0.12,hahahaha,210.00,25.20,184.80
11,1012,22-01-2026,hahahaha,hahaha,NaN,hahahahahaha,7.0,3.25,0.00,hahahaha,22.75,0.00,22.75

In [108]:
# by using dictionary also we can replace

In [109]:
import pandas as pd
a=pd.read_csv("sales.csv")
a.replace({1001:1,1002:2,1003:3})

,order_id,order_date,region,sales_rep,product,category,units,unit_price,discount_pct,customer,gross_sales,discount_amt,net_sales
0,1,03-01-2026,North,Asha,Notebook,Stationery,10.0,4.50,0.00,Acme Co,45.00,0.00,45.00
1,2,04-01-2026,South,Ben,Pen,Stationery,25.0,1.20,0.05,Beta LLC,30.00,1.50,28.50
2,3,06-01-2026,East,Chen,Desk Lamp,Office,3.0,18.99,0.10,Cedar Inc,56.97,5.70,51.27
3,1004,07-01-2026,West,Dia,Chair,Furniture,2.0,89.00,NaN,Delta Partners,178.00,0.00,178.00
4,1005,09-01-2026,North,Asha,Monitor,Electronics,1.0,159.99,0.08,Echo Corp,159.99,12.80,147.19
5,1006,11-01-2026,South,Ben,Keyboard,Electronics,4.0,24.50,0.00,NaN,98.00,0.00,98.00
6,1007,12-01-2026,East,Chen,Paper,Stationery,50.0,0.10,0.00,Foxtrot Ltd,5.00,0.00,5.00
7,1008,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
8,1009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1010,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.00,0.00,Ibis,55.00,0.00,55.00
10,1011,20-01-2026,East,Chen,Desk,Furniture,1.0,210.00,0.12,Juno,210.00,25.20,184.80
11,1012,22-01-2026,West,Dia,NaN,Office,7.0,3.25,0.00,Kilo,22.75,0.00,22.75

In [110]:
# To replace backward and forward data
import pandas as pd
import numpy as np

a = pd.read_csv("sales.csv")

a = a.replace(0.00, np.nan).ffill()
a

,order_id,order_date,region,sales_rep,product,category,units,unit_price,discount_pct,customer,gross_sales,discount_amt,net_sales
0,1001,03-01-2026,North,Asha,Notebook,Stationery,10.0,4.50,NaN,Acme Co,45.00,NaN,45.00
1,1002,04-01-2026,South,Ben,Pen,Stationery,25.0,1.20,0.05,Beta LLC,30.00,1.50,28.50
2,1003,06-01-2026,East,Chen,Desk Lamp,Office,3.0,18.99,0.10,Cedar Inc,56.97,5.70,51.27
3,1004,07-01-2026,West,Dia,Chair,Furniture,2.0,89.00,0.10,Delta Partners,178.00,5.70,178.00
4,1005,09-01-2026,North,Asha,Monitor,Electronics,1.0,159.99,0.08,Echo Corp,159.99,12.80,147.19
5,1006,11-01-2026,South,Ben,Keyboard,Electronics,4.0,24.50,0.08,Echo Corp,98.00,12.80,98.00
6,1007,12-01-2026,East,Chen,Paper,Stationery,50.0,0.10,0.08,Foxtrot Ltd,5.00,12.80,5.00
7,1008,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
8,1009,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
9,1010,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.00,0.15,Ibis,55.00,5.06,55.00
10,1011,20-01-2026,East,Chen,Desk,Furniture,1.0,210.00,0.12,Juno,210.00,25.20,184.80
11,1012,22-01-2026,West,Dia,Desk,Office,7.0,3.25,0.12,Kilo,22.75,25.20,22.75

In [111]:
import pandas as pd
import numpy as np

a = pd.read_csv("sales.csv")

a = a.replace(0.00, np.nan).bfill()
a

,order_id,order_date,region,sales_rep,product,category,units,unit_price,discount_pct,customer,gross_sales,discount_amt,net_sales
0,1001,03-01-2026,North,Asha,Notebook,Stationery,10.0,4.50,0.05,Acme Co,45.00,1.50,45.00
1,1002,04-01-2026,South,Ben,Pen,Stationery,25.0,1.20,0.05,Beta LLC,30.00,1.50,28.50
2,1003,06-01-2026,East,Chen,Desk Lamp,Office,3.0,18.99,0.10,Cedar Inc,56.97,5.70,51.27
3,1004,07-01-2026,West,Dia,Chair,Furniture,2.0,89.00,0.08,Delta Partners,178.00,12.80,178.00
4,1005,09-01-2026,North,Asha,Monitor,Electronics,1.0,159.99,0.08,Echo Corp,159.99,12.80,147.19
5,1006,11-01-2026,South,Ben,Keyboard,Electronics,4.0,24.50,0.15,Foxtrot Ltd,98.00,5.06,98.00
6,1007,12-01-2026,East,Chen,Paper,Stationery,50.0,0.10,0.15,Foxtrot Ltd,5.00,5.06,5.00
7,1008,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
8,1009,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.00,0.12,Ibis,55.00,25.20,55.00
9,1010,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.00,0.12,Ibis,55.00,25.20,55.00
10,1011,20-01-2026,East,Chen,Desk,Furniture,1.0,210.00,0.12,Juno,210.00,25.20,184.80
11,1012,22-01-2026,West,Dia,NaN,Office,7.0,3.25,NaN,Kilo,22.75,NaN,22.75

In [112]:
a = a.replace(0.00, np.nan).ffill(limit=1) # limits the value to the given limit
a

,order_id,order_date,region,sales_rep,product,category,units,unit_price,discount_pct,customer,gross_sales,discount_amt,net_sales
0,1001,03-01-2026,North,Asha,Notebook,Stationery,10.0,4.50,0.05,Acme Co,45.00,1.50,45.00
1,1002,04-01-2026,South,Ben,Pen,Stationery,25.0,1.20,0.05,Beta LLC,30.00,1.50,28.50
2,1003,06-01-2026,East,Chen,Desk Lamp,Office,3.0,18.99,0.10,Cedar Inc,56.97,5.70,51.27
3,1004,07-01-2026,West,Dia,Chair,Furniture,2.0,89.00,0.08,Delta Partners,178.00,12.80,178.00
4,1005,09-01-2026,North,Asha,Monitor,Electronics,1.0,159.99,0.08,Echo Corp,159.99,12.80,147.19
5,1006,11-01-2026,South,Ben,Keyboard,Electronics,4.0,24.50,0.15,Foxtrot Ltd,98.00,5.06,98.00
6,1007,12-01-2026,East,Chen,Paper,Stationery,50.0,0.10,0.15,Foxtrot Ltd,5.00,5.06,5.00
7,1008,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
8,1009,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.00,0.12,Ibis,55.00,25.20,55.00
9,1010,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.00,0.12,Ibis,55.00,25.20,55.00
10,1011,20-01-2026,East,Chen,Desk,Furniture,1.0,210.00,0.12,Juno,210.00,25.20,184.80
11,1012,22-01-2026,West,Dia,Desk,Office,7.0,3.25,0.12,Kilo,22.75,25.20,22.75

In [113]:
a.replace(0.00,np.nan).ffill(limit=1,inplace=True)
a

,order_id,order_date,region,sales_rep,product,category,units,unit_price,discount_pct,customer,gross_sales,discount_amt,net_sales
0,1001,03-01-2026,North,Asha,Notebook,Stationery,10.0,4.50,0.05,Acme Co,45.00,1.50,45.00
1,1002,04-01-2026,South,Ben,Pen,Stationery,25.0,1.20,0.05,Beta LLC,30.00,1.50,28.50
2,1003,06-01-2026,East,Chen,Desk Lamp,Office,3.0,18.99,0.10,Cedar Inc,56.97,5.70,51.27
3,1004,07-01-2026,West,Dia,Chair,Furniture,2.0,89.00,0.08,Delta Partners,178.00,12.80,178.00
4,1005,09-01-2026,North,Asha,Monitor,Electronics,1.0,159.99,0.08,Echo Corp,159.99,12.80,147.19
5,1006,11-01-2026,South,Ben,Keyboard,Electronics,4.0,24.50,0.15,Foxtrot Ltd,98.00,5.06,98.00
6,1007,12-01-2026,East,Chen,Paper,Stationery,50.0,0.10,0.15,Foxtrot Ltd,5.00,5.06,5.00
7,1008,14-01-2026,West,Dia,Stapler,Office,5.0,6.75,0.15,Gamma Group,33.75,5.06,28.69
8,1009,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.00,0.12,Ibis,55.00,25.20,55.00
9,1010,18-01-2026,South,Ben,Whiteboard,Office,1.0,55.00,0.12,Ibis,55.00,25.20,55.00
10,1011,20-01-2026,East,Chen,Desk,Furniture,1.0,210.00,0.12,Juno,210.00,25.20,184.80
11,1012,22-01-2026,West,Dia,Desk,Office,7.0,3.25,0.12,Kilo,22.75,25.20,22.75

In [114]:
# Interpolate

from google.colab import files
uploaded = files.upload()

Saving sales1.csv to sales1.csv

In [115]:
import pandas as pd
a=pd.read_csv("sales1.csv")
a

    Order_ID     Product Region  Sales_Amount  Quantity  Discount  Profit
0       1001      Laptop  North       55000.0       2.0      0.10  5000.0
1       1002       Mouse  South        1200.0       5.0       NaN   300.0
2       1003    Keyboard   East           NaN       3.0      0.05     NaN
3       1004     Monitor   West       18000.0       NaN      0.08  1200.0
4       1005     Printer  North       15000.0       2.0       NaN     NaN
5       1006      Tablet  South       22000.0       1.0      0.12  2500.0
6       1007       Phone   East           NaN       4.0      0.09  3500.0
7       1008  Headphones   West        1800.0       6.0       NaN     NaN
8       1009      Camera  North       45000.0       1.0      0.15  6000.0
9       1010     Speaker  South        3500.0       NaN      0.05     NaN
10      1011  Smartwatch   East           NaN       NaN      0.10  1800.0
11      1012      Router   West        2800.0       2.0       NaN   500.0

In [116]:
# to fill missing value automatically

# a.interpolate() it will not work on alphabets only accepts when it is numerical

a = a.apply(pd.to_numeric, errors='coerce')
a = a.interpolate()
a

    Order_ID  Product  Region  Sales_Amount  Quantity  Discount  Profit
0       1001      NaN     NaN       55000.0  2.000000     0.100  5000.0
1       1002      NaN     NaN        1200.0  5.000000     0.075   300.0
2       1003      NaN     NaN        9600.0  3.000000     0.050   750.0
3       1004      NaN     NaN       18000.0  2.500000     0.080  1200.0
4       1005      NaN     NaN       15000.0  2.000000     0.100  1850.0
5       1006      NaN     NaN       22000.0  1.000000     0.120  2500.0
6       1007      NaN     NaN       11900.0  4.000000     0.090  3500.0
7       1008      NaN     NaN        1800.0  6.000000     0.120  4750.0
8       1009      NaN     NaN       45000.0  1.000000     0.150  6000.0
9       1010      NaN     NaN        3500.0  1.333333     0.050  3900.0
10      1011      NaN     NaN        3150.0  1.666667     0.100  1800.0
11      1012      NaN     NaN        2800.0  2.000000     0.100   500.0

In [117]:
print(a.dtypes)

Order_ID          int64
Product         float64
Region          float64
Sales_Amount    float64
Quantity        float64
Discount        float64
Profit          float64
dtype: object

In [118]:
import pandas as pd
a=pd.read_csv("sales1.csv")
a

    Order_ID     Product Region  Sales_Amount  Quantity  Discount  Profit
0       1001      Laptop  North       55000.0       2.0      0.10  5000.0
1       1002       Mouse  South        1200.0       5.0       NaN   300.0
2       1003    Keyboard   East           NaN       3.0      0.05     NaN
3       1004     Monitor   West       18000.0       NaN      0.08  1200.0
4       1005     Printer  North       15000.0       2.0       NaN     NaN
5       1006      Tablet  South       22000.0       1.0      0.12  2500.0
6       1007       Phone   East           NaN       4.0      0.09  3500.0
7       1008  Headphones   West        1800.0       6.0       NaN     NaN
8       1009      Camera  North       45000.0       1.0      0.15  6000.0
9       1010     Speaker  South        3500.0       NaN      0.05     NaN
10      1011  Smartwatch   East           NaN       NaN      0.10  1800.0
11      1012      Router   West        2800.0       2.0       NaN   500.0

In [119]:
a = a.apply(pd.to_numeric, errors='coerce')
a.interpolate(limit=1)

    Order_ID  Product  Region  Sales_Amount  Quantity  Discount  Profit
0       1001      NaN     NaN       55000.0  2.000000     0.100  5000.0
1       1002      NaN     NaN        1200.0  5.000000     0.075   300.0
2       1003      NaN     NaN        9600.0  3.000000     0.050   750.0
3       1004      NaN     NaN       18000.0  2.500000     0.080  1200.0
4       1005      NaN     NaN       15000.0  2.000000     0.100  1850.0
5       1006      NaN     NaN       22000.0  1.000000     0.120  2500.0
6       1007      NaN     NaN       11900.0  4.000000     0.090  3500.0
7       1008      NaN     NaN        1800.0  6.000000     0.120  4750.0
8       1009      NaN     NaN       45000.0  1.000000     0.150  6000.0
9       1010      NaN     NaN        3500.0  1.333333     0.050  3900.0
10      1011      NaN     NaN        3150.0       NaN     0.100  1800.0
11      1012      NaN     NaN        2800.0  2.000000     0.100   500.0

In [120]:
a.interpolate(limit_direction="backward", limit=2)

    Order_ID  Product  Region  Sales_Amount  Quantity  Discount  Profit
0       1001      NaN     NaN       55000.0  2.000000     0.100  5000.0
1       1002      NaN     NaN        1200.0  5.000000     0.075   300.0
2       1003      NaN     NaN        9600.0  3.000000     0.050   750.0
3       1004      NaN     NaN       18000.0  2.500000     0.080  1200.0
4       1005      NaN     NaN       15000.0  2.000000     0.100  1850.0
5       1006      NaN     NaN       22000.0  1.000000     0.120  2500.0
6       1007      NaN     NaN       11900.0  4.000000     0.090  3500.0
7       1008      NaN     NaN        1800.0  6.000000     0.120  4750.0
8       1009      NaN     NaN       45000.0  1.000000     0.150  6000.0
9       1010      NaN     NaN        3500.0  1.333333     0.050  3900.0
10      1011      NaN     NaN        3150.0  1.666667     0.100  1800.0
11      1012      NaN     NaN        2800.0  2.000000       NaN   500.0

In [121]:
a.interpolate(limit_area="outside") # outside keeps the block as it is

    Order_ID  Product  Region  Sales_Amount  Quantity  Discount  Profit
0       1001      NaN     NaN       55000.0       2.0      0.10  5000.0
1       1002      NaN     NaN        1200.0       5.0       NaN   300.0
2       1003      NaN     NaN           NaN       3.0      0.05     NaN
3       1004      NaN     NaN       18000.0       NaN      0.08  1200.0
4       1005      NaN     NaN       15000.0       2.0       NaN     NaN
5       1006      NaN     NaN       22000.0       1.0      0.12  2500.0
6       1007      NaN     NaN           NaN       4.0      0.09  3500.0
7       1008      NaN     NaN        1800.0       6.0       NaN     NaN
8       1009      NaN     NaN       45000.0       1.0      0.15  6000.0
9       1010      NaN     NaN        3500.0       NaN      0.05     NaN
10      1011      NaN     NaN           NaN       NaN      0.10  1800.0
11      1012      NaN     NaN        2800.0       2.0      0.10   500.0

In [122]:
a.interpolate(limit_area="inside")

    Order_ID  Product  Region  Sales_Amount  Quantity  Discount  Profit
0       1001      NaN     NaN       55000.0  2.000000     0.100  5000.0
1       1002      NaN     NaN        1200.0  5.000000     0.075   300.0
2       1003      NaN     NaN        9600.0  3.000000     0.050   750.0
3       1004      NaN     NaN       18000.0  2.500000     0.080  1200.0
4       1005      NaN     NaN       15000.0  2.000000     0.100  1850.0
5       1006      NaN     NaN       22000.0  1.000000     0.120  2500.0
6       1007      NaN     NaN       11900.0  4.000000     0.090  3500.0
7       1008      NaN     NaN        1800.0  6.000000     0.120  4750.0
8       1009      NaN     NaN       45000.0  1.000000     0.150  6000.0
9       1010      NaN     NaN        3500.0  1.333333     0.050  3900.0
10      1011      NaN     NaN        3150.0  1.666667     0.100  1800.0
11      1012      NaN     NaN        2800.0  2.000000       NaN   500.0

In [123]:
# merge and concat in pandas

In [124]:
# merge

import pandas as pd

a=pd.DataFrame({"A":[1,3,5,7],"B":[2,4,6,8]})
b=pd.DataFrame({"A":[1,3,5,7],"C":[11,12,13,14]})

pd.merge(a,b,on="A")

# A is the comman part only the basis of comman data the dataframe will be produced

   A  B   C
0  1  2  11
1  3  4  12
2  5  6  13
3  7  8  14

In [125]:
pd.merge(b,a,on="A")

   A   C  B
0  1  11  2
1  3  12  4
2  5  13  6
3  7  14  8

In [126]:
a=pd.DataFrame({"A":[1,3,5,7],"B":[2,4,6,8]})
b=pd.DataFrame({"A":[1,3,5,6],"C":[11,12,13,14]})  # 7 and 6 miss match

pd.merge(a,b,on="A")

   A  B   C
0  1  2  11
1  3  4  12
2  5  6  13

In [127]:
# pd.merge(a,b, how= "inner"/"outer"/"left"/"right")

In [128]:
pd.merge(a,b, how= "inner")

   A  B   C
0  1  2  11
1  3  4  12
2  5  6  13

In [129]:
pd.merge(a,b, how= "left")

   A  B     C
0  1  2  11.0
1  3  4  12.0
2  5  6  13.0
3  7  8   NaN

In [130]:
pd.merge(a,b, how= "right")

   A    B   C
0  1  2.0  11
1  3  4.0  12
2  5  6.0  13
3  6  NaN  14

In [131]:
pd.merge(a,b, how= "outer")

   A    B     C
0  1  2.0  11.0
1  3  4.0  12.0
2  5  6.0  13.0
3  6  NaN  14.0
4  7  8.0   NaN

In [132]:
a=pd.DataFrame({"A":[1,3,5,7],"B":[2,4,6,8]})
b=pd.DataFrame({"A":[1,3,5,7],"B":[11,12,13,14]})

pd.merge(a,b)

# nothing will bw shown when bth the names are same

Empty DataFrame
Columns: [A, B]
Index: []

In [133]:
a=pd.DataFrame({"A":[1,3,5,7],"B":[2,4,6,8]})
b=pd.DataFrame({"A":[1,3,5,6],"B":[11,12,13,14]})

pd.merge(a,b,left_index=True,right_index=True)

   A_x  B_x  A_y  B_y
0    1    2    1   11
1    3    4    3   12
2    5    6    5   13
3    7    8    6   14

In [134]:
# to change the name of A_x ...... use suffix

pd.merge(a,b,left_index=True,right_index=True,suffixes=("_job","_bob"))

   A_job  B_job  A_bob  B_bob
0      1      2      1     11
1      3      4      3     12
2      5      6      5     13
3      7      8      6     14

In [135]:
# Concat

In [136]:
import pandas as ps

a= pd.Series([10,20,30])
b= pd.Series([12,14,16,18])

pd.concat([a,b])

0    10
1    20
2    30
0    12
1    14
2    16
3    18
dtype: int64

In [137]:
a=pd.DataFrame({"A":[1,3,5,7],"B":[2,4,6,8]})
b=pd.DataFrame({"A":[1,3,5,6],"B":[11,12,13,14]})

pd.concat([a,b])

   A   B
0  1   2
1  3   4
2  5   6
3  7   8
0  1  11
1  3  12
2  5  13
3  6  14

In [138]:
a=pd.DataFrame({"A":[1,3,5,7],"B":[2,4,6,8]})
b=pd.DataFrame({"C":[1,3,5,6],"V":[11,12,13,14]})

pd.concat([a,b])

     A    B    C     V
0  1.0  2.0  NaN   NaN
1  3.0  4.0  NaN   NaN
2  5.0  6.0  NaN   NaN
3  7.0  8.0  NaN   NaN
0  NaN  NaN  1.0  11.0
1  NaN  NaN  3.0  12.0
2  NaN  NaN  5.0  13.0
3  NaN  NaN  6.0  14.0

In [139]:
a=pd.DataFrame({"A":[1,3,5,7],"B":[2,4,6,8]})
b=pd.DataFrame({"A":[1,3,5,6],"C":[11,12,13,14]})

pd.concat([a,b],axis=1)

   A  B  A   C
0  1  2  1  11
1  3  4  3  12
2  5  6  5  13
3  7  8  6  14

In [140]:
pd.concat([a,b],axis=0)

   A    B     C
0  1  2.0   NaN
1  3  4.0   NaN
2  5  6.0   NaN
3  7  8.0   NaN
0  1  NaN  11.0
1  3  NaN  12.0
2  5  NaN  13.0
3  6  NaN  14.0

In [141]:
# outer - union
# inner - intersection

a=pd.DataFrame({"A":[1,3,5,7],"B":[2,4,6,8]})
b=pd.DataFrame({"A":[1,3],"C":[11,12]})


pd.concat([a,b],axis=1,join="outer")

   A  B    A     C
0  1  2  1.0  11.0
1  3  4  3.0  12.0
2  5  6  NaN   NaN
3  7  8  NaN   NaN

In [142]:
pd.concat([a,b],axis=1,join="inner")

   A  B  A   C
0  1  2  1  11
1  3  4  3  12

In [144]:
pd.concat([a,b],axis=0,keys=["a","b"])

     A    B     C
a 0  1  2.0   NaN
  1  3  4.0   NaN
  2  5  6.0   NaN
  3  7  8.0   NaN
b 0  1  NaN  11.0
  1  3  NaN  12.0

In [145]:
pd.concat([a,b],axis=1,keys=["a","b"])

   a       b
   A  B    A     C
0  1  2  1.0  11.0
1  3  4  3.0  12.0
2  5  6  NaN   NaN
3  7  8  NaN   NaN